namespace QuanLyThuVien.Forms
{
    partial class LendingSlipForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LendingSlipForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            this.panel1 = new System.Windows.Forms.Panel();
            this.refreshBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.searchTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.deleteBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.updateBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.creationBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel2 = new System.Windows.Forms.Panel();
            this.listDGV = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.listDGV)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.refreshBT);
            this.panel1.Controls.Add(this.searchTB);
            this.panel1.Controls.Add(this.deleteBT);
            this.panel1.Controls.Add(this.updateBT);
            this.panel1.Controls.Add(this.creationBT);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1072, 65);
            this.panel1.TabIndex = 11;
            // 
            // refreshBT
            // 
            this.refreshBT.AllowAnimations = true;
            this.refreshBT.AllowMouseEffects = true;
            this.refreshBT.AllowToggling = false;
            this.refreshBT.AnimationSpeed = 200;
            this.refreshBT.AutoGenerateColors = false;
            this.refreshBT.AutoRoundBorders = false;
            this.refreshBT.AutoSizeLeftIcon = true;
            this.refreshBT.AutoSizeRightIcon = true;
            this.refreshBT.BackColor = System.Drawing.Color.Transparent;
            this.refreshBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.refreshBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("refreshBT.BackgroundImage")));
            this.refreshBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.refreshBT.ButtonText = "Làm mới";
            this.refreshBT.ButtonTextMarginLeft = 0;
            this.refreshBT.ColorContrastOnClick = 45;
            this.refreshBT.ColorContrastOnHover = 45;
            this.refreshBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.refreshBT.CustomizableEdges = borderEdges5;
            this.refreshBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.refreshBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.refreshBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.refreshBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.refreshBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.refreshBT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.refreshBT.ForeColor = System.Drawing.Color.White;
            this.refreshBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.refreshBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.refreshBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.refreshBT.IconMarginLeft = 11;
            this.refreshBT.IconPadding = 10;
            this.refreshBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.refreshBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.refreshBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.refreshBT.IconSize = 25;
            this.refreshBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.refreshBT.IdleBorderRadius = 8;
            this.refreshBT.IdleBorderThickness = 1;
            this.refreshBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.refreshBT.IdleIconLeftImage = null;
            this.refreshBT.IdleIconRightImage = null;
            this.refreshBT.IndicateFocus = false;
            this.refreshBT.Location = new System.Drawing.Point(480, 10);
            this.refreshBT.Name = "refreshBT";
            this.refreshBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.refreshBT.OnDisabledState.BorderRadius = 8;
            this.refreshBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.refreshBT.OnDisabledState.BorderThickness = 1;
            this.refreshBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.refreshBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.refreshBT.OnDisabledState.IconLeftImage = null;
            this.refreshBT.OnDisabledState.IconRightImage = null;
            this.refreshBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.refreshBT.onHoverState.BorderRadius = 8;
            this.refreshBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.refreshBT.onHoverState.BorderThickness = 1;
            this.refreshBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.refreshBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.refreshBT.onHoverState.IconLeftImage = null;
            this.refreshBT.onHoverState.IconRightImage = null;
            this.refreshBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.refreshBT.OnIdleState.BorderRadius = 8;
            this.refreshBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.refreshBT.OnIdleState.BorderThickness = 1;
            this.refreshBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.refreshBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.refreshBT.OnIdleState.IconLeftImage = null;
            this.refreshBT.OnIdleState.IconRightImage = null;
            this.refreshBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.refreshBT.OnPressedState.BorderRadius = 8;
            this.refreshBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.refreshBT.OnPressedState.BorderThickness = 1;
            this.refreshBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.refreshBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.refreshBT.OnPressedState.IconLeftImage = null;
            this.refreshBT.OnPressedState.IconRightImage = null;
            this.refreshBT.Size = new System.Drawing.Size(150, 39);
            this.refreshBT.TabIndex = 5;
            this.refreshBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.refreshBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.refreshBT.TextMarginLeft = 0;
            this.refreshBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.refreshBT.UseDefaultRadiusAndThickness = true;
            this.refreshBT.Click += new System.EventHandler(this.refreshBT_Click);
            // 
            // searchTB
            // 
            this.searchTB.AcceptsReturn = false;
            this.searchTB.AcceptsTab = false;
            this.searchTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.searchTB.AnimationSpeed = 200;
            this.searchTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.searchTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.searchTB.BackColor = System.Drawing.Color.Transparent;
            this.searchTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("searchTB.BackgroundImage")));
            this.searchTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.searchTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.searchTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.searchTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.searchTB.BorderRadius = 8;
            this.searchTB.BorderThickness = 1;
            this.searchTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.searchTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.searchTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.searchTB.DefaultText = "";
            this.searchTB.FillColor = System.Drawing.Color.White;
            this.searchTB.HideSelection = true;
            this.searchTB.IconLeft = null;
            this.searchTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchTB.IconPadding = 10;
            this.searchTB.IconRight = null;
            this.searchTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.searchTB.Lines = new string[0];
            this.searchTB.Location = new System.Drawing.Point(800, 12);
            this.searchTB.MaxLength = 32767;
            this.searchTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.searchTB.Modified = false;
            this.searchTB.Multiline = false;
            this.searchTB.Name = "searchTB";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchTB.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.searchTB.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchTB.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.searchTB.OnIdleState = stateProperties8;
            this.searchTB.Padding = new System.Windows.Forms.Padding(3);
            this.searchTB.PasswordChar = '\0';
            this.searchTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.searchTB.PlaceholderText = "Enter text";
            this.searchTB.ReadOnly = false;
            this.searchTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.searchTB.SelectedText = "";
            this.searchTB.SelectionLength = 0;
            this.searchTB.SelectionStart = 0;
            this.searchTB.ShortcutsEnabled = true;
            this.searchTB.Size = new System.Drawing.Size(260, 37);
            this.searchTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.searchTB.TabIndex = 3;
            this.searchTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.searchTB.TextMarginBottom = 0;
            this.searchTB.TextMarginLeft = 3;
            this.searchTB.TextMarginTop = 0;
            this.searchTB.TextPlaceholder = "Enter text";
            this.searchTB.UseSystemPasswordChar = false;
            this.searchTB.WordWrap = true;
            // 
            // deleteBT
            // 
            this.deleteBT.AllowAnimations = true;
            this.deleteBT.AllowMouseEffects = true;
            this.deleteBT.AllowToggling = false;
            this.deleteBT.AnimationSpeed = 200;
            this.deleteBT.AutoGenerateColors = false;
            this.deleteBT.AutoRoundBorders = false;
            this.deleteBT.AutoSizeLeftIcon = true;
            this.deleteBT.AutoSizeRightIcon = true;
            this.deleteBT.BackColor = System.Drawing.Color.Transparent;
            this.deleteBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.deleteBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("deleteBT.BackgroundImage")));
            this.deleteBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteBT.ButtonText = "Xóa";
            this.deleteBT.ButtonTextMarginLeft = 0;
            this.deleteBT.ColorContrastOnClick = 45;
            this.deleteBT.ColorContrastOnHover = 45;
            this.deleteBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.deleteBT.CustomizableEdges = borderEdges6;
            this.deleteBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.deleteBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.deleteBT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.deleteBT.ForeColor = System.Drawing.Color.White;
            this.deleteBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.deleteBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.deleteBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.deleteBT.IconMarginLeft = 11;
            this.deleteBT.IconPadding = 10;
            this.deleteBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.deleteBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.deleteBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.deleteBT.IconSize = 25;
            this.deleteBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.deleteBT.IdleBorderRadius = 8;
            this.deleteBT.IdleBorderThickness = 1;
            this.deleteBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.deleteBT.IdleIconLeftImage = null;
            this.deleteBT.IdleIconRightImage = null;
            this.deleteBT.IndicateFocus = false;
            this.deleteBT.Location = new System.Drawing.Point(324, 12);
            this.deleteBT.Name = "deleteBT";
            this.deleteBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.deleteBT.OnDisabledState.BorderRadius = 8;
            this.deleteBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteBT.OnDisabledState.BorderThickness = 1;
            this.deleteBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.deleteBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.deleteBT.OnDisabledState.IconLeftImage = null;
            this.deleteBT.OnDisabledState.IconRightImage = null;
            this.deleteBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.deleteBT.onHoverState.BorderRadius = 8;
            this.deleteBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteBT.onHoverState.BorderThickness = 1;
            this.deleteBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.deleteBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.deleteBT.onHoverState.IconLeftImage = null;
            this.deleteBT.onHoverState.IconRightImage = null;
            this.deleteBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.deleteBT.OnIdleState.BorderRadius = 8;
            this.deleteBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteBT.OnIdleState.BorderThickness = 1;
            this.deleteBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.deleteBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.deleteBT.OnIdleState.IconLeftImage = null;
            this.deleteBT.OnIdleState.IconRightImage = null;
            this.deleteBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.deleteBT.OnPressedState.BorderRadius = 8;
            this.deleteBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.deleteBT.OnPressedState.BorderThickness = 1;
            this.deleteBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.deleteBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.deleteBT.OnPressedState.IconLeftImage = null;
            this.deleteBT.OnPressedState.IconRightImage = null;
            this.deleteBT.Size = new System.Drawing.Size(150, 39);
            this.deleteBT.TabIndex = 2;
            this.deleteBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.deleteBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.deleteBT.TextMarginLeft = 0;
            this.deleteBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.deleteBT.UseDefaultRadiusAndThickness = true;
            this.deleteBT.Click += new System.EventHandler(this.deleteBT_Click);
            // 
            // updateBT
            // 
            this.updateBT.AllowAnimations = true;
            this.updateBT.AllowMouseEffects = true;
            this.updateBT.AllowToggling = false;
            this.updateBT.AnimationSpeed = 200;
            this.updateBT.AutoGenerateColors = false;
            this.updateBT.AutoRoundBorders = false;
            this.updateBT.AutoSizeLeftIcon = true;
            this.updateBT.AutoSizeRightIcon = true;
            this.updateBT.BackColor = System.Drawing.Color.Transparent;
            this.updateBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.updateBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("updateBT.BackgroundImage")));
            this.updateBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateBT.ButtonText = "Sửa";
            this.updateBT.ButtonTextMarginLeft = 0;
            this.updateBT.ColorContrastOnClick = 45;
            this.updateBT.ColorContrastOnHover = 45;
            this.updateBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.updateBT.CustomizableEdges = borderEdges7;
            this.updateBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.updateBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updateBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updateBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updateBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.updateBT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.updateBT.ForeColor = System.Drawing.Color.White;
            this.updateBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.updateBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.updateBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.updateBT.IconMarginLeft = 11;
            this.updateBT.IconPadding = 10;
            this.updateBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.updateBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.updateBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.updateBT.IconSize = 25;
            this.updateBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.updateBT.IdleBorderRadius = 8;
            this.updateBT.IdleBorderThickness = 1;
            this.updateBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.updateBT.IdleIconLeftImage = null;
            this.updateBT.IdleIconRightImage = null;
            this.updateBT.IndicateFocus = false;
            this.updateBT.Location = new System.Drawing.Point(168, 12);
            this.updateBT.Name = "updateBT";
            this.updateBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.updateBT.OnDisabledState.BorderRadius = 8;
            this.updateBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateBT.OnDisabledState.BorderThickness = 1;
            this.updateBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.updateBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.updateBT.OnDisabledState.IconLeftImage = null;
            this.updateBT.OnDisabledState.IconRightImage = null;
            this.updateBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.updateBT.onHoverState.BorderRadius = 8;
            this.updateBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateBT.onHoverState.BorderThickness = 1;
            this.updateBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.updateBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.updateBT.onHoverState.IconLeftImage = null;
            this.updateBT.onHoverState.IconRightImage = null;
            this.updateBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.updateBT.OnIdleState.BorderRadius = 8;
            this.updateBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateBT.OnIdleState.BorderThickness = 1;
            this.updateBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.updateBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.updateBT.OnIdleState.IconLeftImage = null;
            this.updateBT.OnIdleState.IconRightImage = null;
            this.updateBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.updateBT.OnPressedState.BorderRadius = 8;
            this.updateBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.updateBT.OnPressedState.BorderThickness = 1;
            this.updateBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.updateBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.updateBT.OnPressedState.IconLeftImage = null;
            this.updateBT.OnPressedState.IconRightImage = null;
            this.updateBT.Size = new System.Drawing.Size(150, 39);
            this.updateBT.TabIndex = 1;
            this.updateBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.updateBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.updateBT.TextMarginLeft = 0;
            this.updateBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.updateBT.UseDefaultRadiusAndThickness = true;
            this.updateBT.Click += new System.EventHandler(this.updateBT_Click);
            // 
            // creationBT
            // 
            this.creationBT.AllowAnimations = true;
            this.creationBT.AllowMouseEffects = true;
            this.creationBT.AllowToggling = false;
            this.creationBT.AnimationSpeed = 200;
            this.creationBT.AutoGenerateColors = false;
            this.creationBT.AutoRoundBorders = false;
            this.creationBT.AutoSizeLeftIcon = true;
            this.creationBT.AutoSizeRightIcon = true;
            this.creationBT.BackColor = System.Drawing.Color.Transparent;
            this.creationBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.creationBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("creationBT.BackgroundImage")));
            this.creationBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.creationBT.ButtonText = "Tạo";
            this.creationBT.ButtonTextMarginLeft = 0;
            this.creationBT.ColorContrastOnClick = 45;
            this.creationBT.ColorContrastOnHover = 45;
            this.creationBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.creationBT.CustomizableEdges = borderEdges8;
            this.creationBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.creationBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.creationBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.creationBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.creationBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.creationBT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.creationBT.ForeColor = System.Drawing.Color.White;
            this.creationBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.creationBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.creationBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.creationBT.IconMarginLeft = 11;
            this.creationBT.IconPadding = 10;
            this.creationBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.creationBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.creationBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.creationBT.IconSize = 25;
            this.creationBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.creationBT.IdleBorderRadius = 8;
            this.creationBT.IdleBorderThickness = 1;
            this.creationBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.creationBT.IdleIconLeftImage = null;
            this.creationBT.IdleIconRightImage = null;
            this.creationBT.IndicateFocus = false;
            this.creationBT.Location = new System.Drawing.Point(12, 12);
            this.creationBT.Name = "creationBT";
            this.creationBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.creationBT.OnDisabledState.BorderRadius = 8;
            this.creationBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.creationBT.OnDisabledState.BorderThickness = 1;
            this.creationBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.creationBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.creationBT.OnDisabledState.IconLeftImage = null;
            this.creationBT.OnDisabledState.IconRightImage = null;
            this.creationBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.creationBT.onHoverState.BorderRadius = 8;
            this.creationBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.creationBT.onHoverState.BorderThickness = 1;
            this.creationBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.creationBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.creationBT.onHoverState.IconLeftImage = null;
            this.creationBT.onHoverState.IconRightImage = null;
            this.creationBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.creationBT.OnIdleState.BorderRadius = 8;
            this.creationBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.creationBT.OnIdleState.BorderThickness = 1;
            this.creationBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.creationBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.creationBT.OnIdleState.IconLeftImage = null;
            this.creationBT.OnIdleState.IconRightImage = null;
            this.creationBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.creationBT.OnPressedState.BorderRadius = 8;
            this.creationBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.creationBT.OnPressedState.BorderThickness = 1;
            this.creationBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.creationBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.creationBT.OnPressedState.IconLeftImage = null;
            this.creationBT.OnPressedState.IconRightImage = null;
            this.creationBT.Size = new System.Drawing.Size(150, 39);
            this.creationBT.TabIndex = 0;
            this.creationBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.creationBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.creationBT.TextMarginLeft = 0;
            this.creationBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.creationBT.UseDefaultRadiusAndThickness = true;
            this.creationBT.Click += new System.EventHandler(this.creationBT_Click);
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.listDGV);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel2.Location = new System.Drawing.Point(0, 65);
            this.panel2.Name = "panel2";
            this.panel2.Padding = new System.Windows.Forms.Padding(12);
            this.panel2.Size = new System.Drawing.Size(1072, 512);
            this.panel2.TabIndex = 13;
            // 
            // listDGV
            // 
            this.listDGV.AllowCustomTheming = true;
            this.listDGV.AllowUserToAddRows = false;
            this.listDGV.AllowUserToDeleteRows = false;
            this.listDGV.AllowUserToOrderColumns = true;
            this.listDGV.AllowUserToResizeColumns = false;
            this.listDGV.AllowUserToResizeRows = false;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(223)))));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.Black;
            this.listDGV.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle4;
            this.listDGV.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.listDGV.BackgroundColor = System.Drawing.Color.White;
            this.listDGV.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.listDGV.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.listDGV.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.listDGV.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle5;
            this.listDGV.ColumnHeadersHeight = 40;
            this.listDGV.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(223)))));
            this.listDGV.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.listDGV.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.listDGV.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(102)))), ((int)(((byte)(178)))));
            this.listDGV.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.White;
            this.listDGV.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.listDGV.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.listDGV.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.listDGV.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.listDGV.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.listDGV.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.listDGV.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.listDGV.CurrentTheme.Name = null;
            this.listDGV.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(229)))));
            this.listDGV.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.listDGV.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.listDGV.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(102)))), ((int)(((byte)(178)))));
            this.listDGV.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(229)))));
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(102)))), ((int)(((byte)(178)))));
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.listDGV.DefaultCellStyle = dataGridViewCellStyle6;
            this.listDGV.Dock = System.Windows.Forms.DockStyle.Fill;
            this.listDGV.EnableHeadersVisualStyles = false;
            this.listDGV.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.listDGV.HeaderBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.listDGV.HeaderBgColor = System.Drawing.Color.Empty;
            this.listDGV.HeaderForeColor = System.Drawing.Color.White;
            this.listDGV.Location = new System.Drawing.Point(12, 12);
            this.listDGV.Margin = new System.Windows.Forms.Padding(24);
            this.listDGV.Name = "listDGV";
            this.listDGV.ReadOnly = true;
            this.listDGV.RowHeadersVisible = false;
            this.listDGV.RowTemplate.Height = 40;
            this.listDGV.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.listDGV.Size = new System.Drawing.Size(1048, 488);
            this.listDGV.TabIndex = 2;
            this.listDGV.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Navy;
            this.listDGV.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.listDGV_CellDoubleClick);
            // 
            // LendingSlipForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(1072, 577);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.Name = "LendingSlipForm";
            this.Text = "LendingSlipForm";
            this.Shown += new System.EventHandler(this.LendingSlipForm_Shown);
            this.panel1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.listDGV)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton refreshBT;
        private Bunifu.UI.WinForms.BunifuTextBox searchTB;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton deleteBT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton updateBT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton creationBT;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuDataGridView listDGV;
    }
}