namespace QuanLyThuVien.Forms
{
    partial class MainForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges10 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges11 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.logoutBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.liquidatingSlipBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.libraryCardBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.simulationBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lendingSlipBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bookBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.authorBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.readerBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.profileBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel2 = new System.Windows.Forms.Panel();
            this.panel3 = new System.Windows.Forms.Panel();
            this.label1 = new System.Windows.Forms.Label();
            this.contentPanel = new System.Windows.Forms.Panel();
            this.panel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.panel1.Controls.Add(this.logoutBT);
            this.panel1.Controls.Add(this.liquidatingSlipBT);
            this.panel1.Controls.Add(this.libraryCardBT);
            this.panel1.Controls.Add(this.simulationBT);
            this.panel1.Controls.Add(this.lendingSlipBT);
            this.panel1.Controls.Add(this.bookBT);
            this.panel1.Controls.Add(this.authorBT);
            this.panel1.Controls.Add(this.bunifuButton4);
            this.panel1.Controls.Add(this.readerBT);
            this.panel1.Controls.Add(this.bunifuButton2);
            this.panel1.Controls.Add(this.profileBT);
            this.panel1.Controls.Add(this.panel2);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.panel1.ForeColor = System.Drawing.Color.White;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Margin = new System.Windows.Forms.Padding(2);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(287, 763);
            this.panel1.TabIndex = 0;
            // 
            // logoutBT
            // 
            this.logoutBT.AllowAnimations = true;
            this.logoutBT.AllowMouseEffects = true;
            this.logoutBT.AllowToggling = true;
            this.logoutBT.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.logoutBT.AnimationSpeed = 200;
            this.logoutBT.AutoGenerateColors = false;
            this.logoutBT.AutoRoundBorders = false;
            this.logoutBT.AutoSizeLeftIcon = true;
            this.logoutBT.AutoSizeRightIcon = true;
            this.logoutBT.BackColor = System.Drawing.Color.Transparent;
            this.logoutBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.logoutBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("logoutBT.BackgroundImage")));
            this.logoutBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.logoutBT.ButtonText = "Đăng xuất";
            this.logoutBT.ButtonTextMarginLeft = 0;
            this.logoutBT.ColorContrastOnClick = 45;
            this.logoutBT.ColorContrastOnHover = 45;
            this.logoutBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.logoutBT.CustomizableEdges = borderEdges1;
            this.logoutBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.logoutBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.logoutBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.logoutBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.logoutBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.logoutBT.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.logoutBT.ForeColor = System.Drawing.Color.White;
            this.logoutBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.logoutBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.logoutBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.logoutBT.IconMarginLeft = 11;
            this.logoutBT.IconPadding = 10;
            this.logoutBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.logoutBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.logoutBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.logoutBT.IconSize = 25;
            this.logoutBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.logoutBT.IdleBorderRadius = 8;
            this.logoutBT.IdleBorderThickness = 1;
            this.logoutBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.logoutBT.IdleIconLeftImage = null;
            this.logoutBT.IdleIconRightImage = null;
            this.logoutBT.IndicateFocus = false;
            this.logoutBT.Location = new System.Drawing.Point(32, 706);
            this.logoutBT.Name = "logoutBT";
            this.logoutBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.logoutBT.OnDisabledState.BorderRadius = 8;
            this.logoutBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.logoutBT.OnDisabledState.BorderThickness = 1;
            this.logoutBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.logoutBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.logoutBT.OnDisabledState.IconLeftImage = null;
            this.logoutBT.OnDisabledState.IconRightImage = null;
            this.logoutBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.logoutBT.onHoverState.BorderRadius = 8;
            this.logoutBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.logoutBT.onHoverState.BorderThickness = 1;
            this.logoutBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.logoutBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.logoutBT.onHoverState.IconLeftImage = null;
            this.logoutBT.onHoverState.IconRightImage = null;
            this.logoutBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.logoutBT.OnIdleState.BorderRadius = 8;
            this.logoutBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.logoutBT.OnIdleState.BorderThickness = 1;
            this.logoutBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.logoutBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.logoutBT.OnIdleState.IconLeftImage = null;
            this.logoutBT.OnIdleState.IconRightImage = null;
            this.logoutBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.logoutBT.OnPressedState.BorderRadius = 8;
            this.logoutBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.logoutBT.OnPressedState.BorderThickness = 1;
            this.logoutBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.logoutBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.logoutBT.OnPressedState.IconLeftImage = null;
            this.logoutBT.OnPressedState.IconRightImage = null;
            this.logoutBT.Size = new System.Drawing.Size(219, 45);
            this.logoutBT.TabIndex = 11;
            this.logoutBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.logoutBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.logoutBT.TextMarginLeft = 0;
            this.logoutBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.logoutBT.UseDefaultRadiusAndThickness = true;
            this.logoutBT.Click += new System.EventHandler(this.logoutBT_Click);
            // 
            // liquidatingSlipBT
            // 
            this.liquidatingSlipBT.AllowAnimations = true;
            this.liquidatingSlipBT.AllowMouseEffects = true;
            this.liquidatingSlipBT.AllowToggling = true;
            this.liquidatingSlipBT.AnimationSpeed = 200;
            this.liquidatingSlipBT.AutoGenerateColors = false;
            this.liquidatingSlipBT.AutoRoundBorders = false;
            this.liquidatingSlipBT.AutoSizeLeftIcon = true;
            this.liquidatingSlipBT.AutoSizeRightIcon = true;
            this.liquidatingSlipBT.BackColor = System.Drawing.Color.Transparent;
            this.liquidatingSlipBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.liquidatingSlipBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("liquidatingSlipBT.BackgroundImage")));
            this.liquidatingSlipBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.liquidatingSlipBT.ButtonText = "Quản lí phiếu thanh lý";
            this.liquidatingSlipBT.ButtonTextMarginLeft = 0;
            this.liquidatingSlipBT.ColorContrastOnClick = 45;
            this.liquidatingSlipBT.ColorContrastOnHover = 45;
            this.liquidatingSlipBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.liquidatingSlipBT.CustomizableEdges = borderEdges2;
            this.liquidatingSlipBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.liquidatingSlipBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.liquidatingSlipBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.liquidatingSlipBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.liquidatingSlipBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.liquidatingSlipBT.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.liquidatingSlipBT.ForeColor = System.Drawing.Color.White;
            this.liquidatingSlipBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.liquidatingSlipBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.liquidatingSlipBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.liquidatingSlipBT.IconMarginLeft = 11;
            this.liquidatingSlipBT.IconPadding = 10;
            this.liquidatingSlipBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.liquidatingSlipBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.liquidatingSlipBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.liquidatingSlipBT.IconSize = 25;
            this.liquidatingSlipBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.liquidatingSlipBT.IdleBorderRadius = 8;
            this.liquidatingSlipBT.IdleBorderThickness = 1;
            this.liquidatingSlipBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.liquidatingSlipBT.IdleIconLeftImage = null;
            this.liquidatingSlipBT.IdleIconRightImage = null;
            this.liquidatingSlipBT.IndicateFocus = true;
            this.liquidatingSlipBT.Location = new System.Drawing.Point(32, 515);
            this.liquidatingSlipBT.Name = "liquidatingSlipBT";
            this.liquidatingSlipBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.liquidatingSlipBT.OnDisabledState.BorderRadius = 8;
            this.liquidatingSlipBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.liquidatingSlipBT.OnDisabledState.BorderThickness = 1;
            this.liquidatingSlipBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.liquidatingSlipBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.liquidatingSlipBT.OnDisabledState.IconLeftImage = null;
            this.liquidatingSlipBT.OnDisabledState.IconRightImage = null;
            this.liquidatingSlipBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.liquidatingSlipBT.onHoverState.BorderRadius = 8;
            this.liquidatingSlipBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.liquidatingSlipBT.onHoverState.BorderThickness = 1;
            this.liquidatingSlipBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.liquidatingSlipBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.liquidatingSlipBT.onHoverState.IconLeftImage = null;
            this.liquidatingSlipBT.onHoverState.IconRightImage = null;
            this.liquidatingSlipBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.liquidatingSlipBT.OnIdleState.BorderRadius = 8;
            this.liquidatingSlipBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.liquidatingSlipBT.OnIdleState.BorderThickness = 1;
            this.liquidatingSlipBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.liquidatingSlipBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.liquidatingSlipBT.OnIdleState.IconLeftImage = null;
            this.liquidatingSlipBT.OnIdleState.IconRightImage = null;
            this.liquidatingSlipBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.liquidatingSlipBT.OnPressedState.BorderRadius = 8;
            this.liquidatingSlipBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.liquidatingSlipBT.OnPressedState.BorderThickness = 1;
            this.liquidatingSlipBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.liquidatingSlipBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.liquidatingSlipBT.OnPressedState.IconLeftImage = null;
            this.liquidatingSlipBT.OnPressedState.IconRightImage = null;
            this.liquidatingSlipBT.Size = new System.Drawing.Size(219, 45);
            this.liquidatingSlipBT.TabIndex = 10;
            this.liquidatingSlipBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.liquidatingSlipBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.liquidatingSlipBT.TextMarginLeft = 0;
            this.liquidatingSlipBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.liquidatingSlipBT.UseDefaultRadiusAndThickness = true;
            this.liquidatingSlipBT.Click += new System.EventHandler(this.liquidatingSlipBT_Click);
            // 
            // libraryCardBT
            // 
            this.libraryCardBT.AllowAnimations = true;
            this.libraryCardBT.AllowMouseEffects = true;
            this.libraryCardBT.AllowToggling = true;
            this.libraryCardBT.AnimationSpeed = 200;
            this.libraryCardBT.AutoGenerateColors = false;
            this.libraryCardBT.AutoRoundBorders = false;
            this.libraryCardBT.AutoSizeLeftIcon = true;
            this.libraryCardBT.AutoSizeRightIcon = true;
            this.libraryCardBT.BackColor = System.Drawing.Color.Transparent;
            this.libraryCardBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.libraryCardBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("libraryCardBT.BackgroundImage")));
            this.libraryCardBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.libraryCardBT.ButtonText = "Quản lí thẻ thư viện";
            this.libraryCardBT.ButtonTextMarginLeft = 0;
            this.libraryCardBT.ColorContrastOnClick = 45;
            this.libraryCardBT.ColorContrastOnHover = 45;
            this.libraryCardBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.libraryCardBT.CustomizableEdges = borderEdges3;
            this.libraryCardBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.libraryCardBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.libraryCardBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.libraryCardBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.libraryCardBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.libraryCardBT.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.libraryCardBT.ForeColor = System.Drawing.Color.White;
            this.libraryCardBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.libraryCardBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.libraryCardBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.libraryCardBT.IconMarginLeft = 11;
            this.libraryCardBT.IconPadding = 10;
            this.libraryCardBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.libraryCardBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.libraryCardBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.libraryCardBT.IconSize = 25;
            this.libraryCardBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.libraryCardBT.IdleBorderRadius = 8;
            this.libraryCardBT.IdleBorderThickness = 1;
            this.libraryCardBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.libraryCardBT.IdleIconLeftImage = null;
            this.libraryCardBT.IdleIconRightImage = null;
            this.libraryCardBT.IndicateFocus = true;
            this.libraryCardBT.Location = new System.Drawing.Point(32, 362);
            this.libraryCardBT.Name = "libraryCardBT";
            this.libraryCardBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.libraryCardBT.OnDisabledState.BorderRadius = 8;
            this.libraryCardBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.libraryCardBT.OnDisabledState.BorderThickness = 1;
            this.libraryCardBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.libraryCardBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.libraryCardBT.OnDisabledState.IconLeftImage = null;
            this.libraryCardBT.OnDisabledState.IconRightImage = null;
            this.libraryCardBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.libraryCardBT.onHoverState.BorderRadius = 8;
            this.libraryCardBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.libraryCardBT.onHoverState.BorderThickness = 1;
            this.libraryCardBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.libraryCardBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.libraryCardBT.onHoverState.IconLeftImage = null;
            this.libraryCardBT.onHoverState.IconRightImage = null;
            this.libraryCardBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.libraryCardBT.OnIdleState.BorderRadius = 8;
            this.libraryCardBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.libraryCardBT.OnIdleState.BorderThickness = 1;
            this.libraryCardBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.libraryCardBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.libraryCardBT.OnIdleState.IconLeftImage = null;
            this.libraryCardBT.OnIdleState.IconRightImage = null;
            this.libraryCardBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.libraryCardBT.OnPressedState.BorderRadius = 8;
            this.libraryCardBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.libraryCardBT.OnPressedState.BorderThickness = 1;
            this.libraryCardBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.libraryCardBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.libraryCardBT.OnPressedState.IconLeftImage = null;
            this.libraryCardBT.OnPressedState.IconRightImage = null;
            this.libraryCardBT.Size = new System.Drawing.Size(219, 45);
            this.libraryCardBT.TabIndex = 9;
            this.libraryCardBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.libraryCardBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.libraryCardBT.TextMarginLeft = 0;
            this.libraryCardBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.libraryCardBT.UseDefaultRadiusAndThickness = true;
            this.libraryCardBT.Click += new System.EventHandler(this.libraryCardBT_Click);
            // 
            // simulationBT
            // 
            this.simulationBT.AllowAnimations = true;
            this.simulationBT.AllowMouseEffects = true;
            this.simulationBT.AllowToggling = true;
            this.simulationBT.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.simulationBT.AnimationSpeed = 200;
            this.simulationBT.AutoGenerateColors = false;
            this.simulationBT.AutoRoundBorders = false;
            this.simulationBT.AutoSizeLeftIcon = true;
            this.simulationBT.AutoSizeRightIcon = true;
            this.simulationBT.BackColor = System.Drawing.Color.Transparent;
            this.simulationBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.simulationBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("simulationBT.BackgroundImage")));
            this.simulationBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.simulationBT.ButtonText = "Mô phỏng";
            this.simulationBT.ButtonTextMarginLeft = 0;
            this.simulationBT.ColorContrastOnClick = 45;
            this.simulationBT.ColorContrastOnHover = 45;
            this.simulationBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.simulationBT.CustomizableEdges = borderEdges4;
            this.simulationBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.simulationBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.simulationBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.simulationBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.simulationBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.simulationBT.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.simulationBT.ForeColor = System.Drawing.Color.White;
            this.simulationBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.simulationBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.simulationBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.simulationBT.IconMarginLeft = 11;
            this.simulationBT.IconPadding = 10;
            this.simulationBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.simulationBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.simulationBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.simulationBT.IconSize = 25;
            this.simulationBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.simulationBT.IdleBorderRadius = 8;
            this.simulationBT.IdleBorderThickness = 1;
            this.simulationBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.simulationBT.IdleIconLeftImage = null;
            this.simulationBT.IdleIconRightImage = null;
            this.simulationBT.IndicateFocus = true;
            this.simulationBT.Location = new System.Drawing.Point(32, 655);
            this.simulationBT.Name = "simulationBT";
            this.simulationBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.simulationBT.OnDisabledState.BorderRadius = 8;
            this.simulationBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.simulationBT.OnDisabledState.BorderThickness = 1;
            this.simulationBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.simulationBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.simulationBT.OnDisabledState.IconLeftImage = null;
            this.simulationBT.OnDisabledState.IconRightImage = null;
            this.simulationBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.simulationBT.onHoverState.BorderRadius = 8;
            this.simulationBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.simulationBT.onHoverState.BorderThickness = 1;
            this.simulationBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.simulationBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.simulationBT.onHoverState.IconLeftImage = null;
            this.simulationBT.onHoverState.IconRightImage = null;
            this.simulationBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.simulationBT.OnIdleState.BorderRadius = 8;
            this.simulationBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.simulationBT.OnIdleState.BorderThickness = 1;
            this.simulationBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.simulationBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.simulationBT.OnIdleState.IconLeftImage = null;
            this.simulationBT.OnIdleState.IconRightImage = null;
            this.simulationBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.simulationBT.OnPressedState.BorderRadius = 8;
            this.simulationBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.simulationBT.OnPressedState.BorderThickness = 1;
            this.simulationBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.simulationBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.simulationBT.OnPressedState.IconLeftImage = null;
            this.simulationBT.OnPressedState.IconRightImage = null;
            this.simulationBT.Size = new System.Drawing.Size(219, 45);
            this.simulationBT.TabIndex = 8;
            this.simulationBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.simulationBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.simulationBT.TextMarginLeft = 0;
            this.simulationBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.simulationBT.UseDefaultRadiusAndThickness = true;
            this.simulationBT.Click += new System.EventHandler(this.simulationBT_Click);
            // 
            // lendingSlipBT
            // 
            this.lendingSlipBT.AllowAnimations = true;
            this.lendingSlipBT.AllowMouseEffects = true;
            this.lendingSlipBT.AllowToggling = true;
            this.lendingSlipBT.AnimationSpeed = 200;
            this.lendingSlipBT.AutoGenerateColors = false;
            this.lendingSlipBT.AutoRoundBorders = false;
            this.lendingSlipBT.AutoSizeLeftIcon = true;
            this.lendingSlipBT.AutoSizeRightIcon = true;
            this.lendingSlipBT.BackColor = System.Drawing.Color.Transparent;
            this.lendingSlipBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.lendingSlipBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lendingSlipBT.BackgroundImage")));
            this.lendingSlipBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.lendingSlipBT.ButtonText = "Quản lí phiếu mượn";
            this.lendingSlipBT.ButtonTextMarginLeft = 0;
            this.lendingSlipBT.ColorContrastOnClick = 45;
            this.lendingSlipBT.ColorContrastOnHover = 45;
            this.lendingSlipBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.lendingSlipBT.CustomizableEdges = borderEdges5;
            this.lendingSlipBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.lendingSlipBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.lendingSlipBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lendingSlipBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.lendingSlipBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.lendingSlipBT.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lendingSlipBT.ForeColor = System.Drawing.Color.White;
            this.lendingSlipBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.lendingSlipBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.lendingSlipBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.lendingSlipBT.IconMarginLeft = 11;
            this.lendingSlipBT.IconPadding = 10;
            this.lendingSlipBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.lendingSlipBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.lendingSlipBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.lendingSlipBT.IconSize = 25;
            this.lendingSlipBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.lendingSlipBT.IdleBorderRadius = 8;
            this.lendingSlipBT.IdleBorderThickness = 1;
            this.lendingSlipBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.lendingSlipBT.IdleIconLeftImage = null;
            this.lendingSlipBT.IdleIconRightImage = null;
            this.lendingSlipBT.IndicateFocus = true;
            this.lendingSlipBT.Location = new System.Drawing.Point(32, 464);
            this.lendingSlipBT.Name = "lendingSlipBT";
            this.lendingSlipBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.lendingSlipBT.OnDisabledState.BorderRadius = 8;
            this.lendingSlipBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.lendingSlipBT.OnDisabledState.BorderThickness = 1;
            this.lendingSlipBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lendingSlipBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.lendingSlipBT.OnDisabledState.IconLeftImage = null;
            this.lendingSlipBT.OnDisabledState.IconRightImage = null;
            this.lendingSlipBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.lendingSlipBT.onHoverState.BorderRadius = 8;
            this.lendingSlipBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.lendingSlipBT.onHoverState.BorderThickness = 1;
            this.lendingSlipBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.lendingSlipBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.lendingSlipBT.onHoverState.IconLeftImage = null;
            this.lendingSlipBT.onHoverState.IconRightImage = null;
            this.lendingSlipBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.lendingSlipBT.OnIdleState.BorderRadius = 8;
            this.lendingSlipBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.lendingSlipBT.OnIdleState.BorderThickness = 1;
            this.lendingSlipBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.lendingSlipBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.lendingSlipBT.OnIdleState.IconLeftImage = null;
            this.lendingSlipBT.OnIdleState.IconRightImage = null;
            this.lendingSlipBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.lendingSlipBT.OnPressedState.BorderRadius = 8;
            this.lendingSlipBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.lendingSlipBT.OnPressedState.BorderThickness = 1;
            this.lendingSlipBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.lendingSlipBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.lendingSlipBT.OnPressedState.IconLeftImage = null;
            this.lendingSlipBT.OnPressedState.IconRightImage = null;
            this.lendingSlipBT.Size = new System.Drawing.Size(219, 45);
            this.lendingSlipBT.TabIndex = 7;
            this.lendingSlipBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.lendingSlipBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.lendingSlipBT.TextMarginLeft = 0;
            this.lendingSlipBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.lendingSlipBT.UseDefaultRadiusAndThickness = true;
            this.lendingSlipBT.Click += new System.EventHandler(this.lendingSlipBT_Click);
            // 
            // bookBT
            // 
            this.bookBT.AllowAnimations = true;
            this.bookBT.AllowMouseEffects = true;
            this.bookBT.AllowToggling = true;
            this.bookBT.AnimationSpeed = 200;
            this.bookBT.AutoGenerateColors = false;
            this.bookBT.AutoRoundBorders = false;
            this.bookBT.AutoSizeLeftIcon = true;
            this.bookBT.AutoSizeRightIcon = true;
            this.bookBT.BackColor = System.Drawing.Color.Transparent;
            this.bookBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bookBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bookBT.BackgroundImage")));
            this.bookBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bookBT.ButtonText = "Quản lí sách";
            this.bookBT.ButtonTextMarginLeft = 0;
            this.bookBT.ColorContrastOnClick = 45;
            this.bookBT.ColorContrastOnHover = 45;
            this.bookBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.bookBT.CustomizableEdges = borderEdges6;
            this.bookBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bookBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bookBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bookBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bookBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bookBT.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bookBT.ForeColor = System.Drawing.Color.White;
            this.bookBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bookBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bookBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bookBT.IconMarginLeft = 11;
            this.bookBT.IconPadding = 10;
            this.bookBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bookBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bookBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bookBT.IconSize = 25;
            this.bookBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bookBT.IdleBorderRadius = 8;
            this.bookBT.IdleBorderThickness = 1;
            this.bookBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bookBT.IdleIconLeftImage = null;
            this.bookBT.IdleIconRightImage = null;
            this.bookBT.IndicateFocus = true;
            this.bookBT.Location = new System.Drawing.Point(32, 209);
            this.bookBT.Name = "bookBT";
            this.bookBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bookBT.OnDisabledState.BorderRadius = 8;
            this.bookBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bookBT.OnDisabledState.BorderThickness = 1;
            this.bookBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bookBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bookBT.OnDisabledState.IconLeftImage = null;
            this.bookBT.OnDisabledState.IconRightImage = null;
            this.bookBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.bookBT.onHoverState.BorderRadius = 8;
            this.bookBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bookBT.onHoverState.BorderThickness = 1;
            this.bookBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.bookBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bookBT.onHoverState.IconLeftImage = null;
            this.bookBT.onHoverState.IconRightImage = null;
            this.bookBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bookBT.OnIdleState.BorderRadius = 8;
            this.bookBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bookBT.OnIdleState.BorderThickness = 1;
            this.bookBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bookBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bookBT.OnIdleState.IconLeftImage = null;
            this.bookBT.OnIdleState.IconRightImage = null;
            this.bookBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.bookBT.OnPressedState.BorderRadius = 8;
            this.bookBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bookBT.OnPressedState.BorderThickness = 1;
            this.bookBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.bookBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bookBT.OnPressedState.IconLeftImage = null;
            this.bookBT.OnPressedState.IconRightImage = null;
            this.bookBT.Size = new System.Drawing.Size(219, 45);
            this.bookBT.TabIndex = 6;
            this.bookBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bookBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bookBT.TextMarginLeft = 0;
            this.bookBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.bookBT.UseDefaultRadiusAndThickness = true;
            this.bookBT.Click += new System.EventHandler(this.bookBT_Click);
            // 
            // authorBT
            // 
            this.authorBT.AllowAnimations = true;
            this.authorBT.AllowMouseEffects = true;
            this.authorBT.AllowToggling = true;
            this.authorBT.AnimationSpeed = 200;
            this.authorBT.AutoGenerateColors = false;
            this.authorBT.AutoRoundBorders = false;
            this.authorBT.AutoSizeLeftIcon = true;
            this.authorBT.AutoSizeRightIcon = true;
            this.authorBT.BackColor = System.Drawing.Color.Transparent;
            this.authorBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.authorBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("authorBT.BackgroundImage")));
            this.authorBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.authorBT.ButtonText = "Quản lí tác giả";
            this.authorBT.ButtonTextMarginLeft = 0;
            this.authorBT.ColorContrastOnClick = 45;
            this.authorBT.ColorContrastOnHover = 45;
            this.authorBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.authorBT.CustomizableEdges = borderEdges7;
            this.authorBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.authorBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.authorBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.authorBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.authorBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.authorBT.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.authorBT.ForeColor = System.Drawing.Color.White;
            this.authorBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.authorBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.authorBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.authorBT.IconMarginLeft = 11;
            this.authorBT.IconPadding = 10;
            this.authorBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.authorBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.authorBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.authorBT.IconSize = 25;
            this.authorBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.authorBT.IdleBorderRadius = 8;
            this.authorBT.IdleBorderThickness = 1;
            this.authorBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.authorBT.IdleIconLeftImage = null;
            this.authorBT.IdleIconRightImage = null;
            this.authorBT.IndicateFocus = true;
            this.authorBT.Location = new System.Drawing.Point(32, 413);
            this.authorBT.Name = "authorBT";
            this.authorBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.authorBT.OnDisabledState.BorderRadius = 8;
            this.authorBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.authorBT.OnDisabledState.BorderThickness = 1;
            this.authorBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.authorBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.authorBT.OnDisabledState.IconLeftImage = null;
            this.authorBT.OnDisabledState.IconRightImage = null;
            this.authorBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.authorBT.onHoverState.BorderRadius = 8;
            this.authorBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.authorBT.onHoverState.BorderThickness = 1;
            this.authorBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.authorBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.authorBT.onHoverState.IconLeftImage = null;
            this.authorBT.onHoverState.IconRightImage = null;
            this.authorBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.authorBT.OnIdleState.BorderRadius = 8;
            this.authorBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.authorBT.OnIdleState.BorderThickness = 1;
            this.authorBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.authorBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.authorBT.OnIdleState.IconLeftImage = null;
            this.authorBT.OnIdleState.IconRightImage = null;
            this.authorBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.authorBT.OnPressedState.BorderRadius = 8;
            this.authorBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.authorBT.OnPressedState.BorderThickness = 1;
            this.authorBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.authorBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.authorBT.OnPressedState.IconLeftImage = null;
            this.authorBT.OnPressedState.IconRightImage = null;
            this.authorBT.Size = new System.Drawing.Size(219, 45);
            this.authorBT.TabIndex = 5;
            this.authorBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.authorBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.authorBT.TextMarginLeft = 0;
            this.authorBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.authorBT.UseDefaultRadiusAndThickness = true;
            this.authorBT.Click += new System.EventHandler(this.authorBT_Click);
            // 
            // bunifuButton4
            // 
            this.bunifuButton4.AllowAnimations = true;
            this.bunifuButton4.AllowMouseEffects = true;
            this.bunifuButton4.AllowToggling = true;
            this.bunifuButton4.AnimationSpeed = 200;
            this.bunifuButton4.AutoGenerateColors = false;
            this.bunifuButton4.AutoRoundBorders = false;
            this.bunifuButton4.AutoSizeLeftIcon = true;
            this.bunifuButton4.AutoSizeRightIcon = true;
            this.bunifuButton4.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton4.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton4.BackgroundImage")));
            this.bunifuButton4.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.ButtonText = "Quản lí thủ thư";
            this.bunifuButton4.ButtonTextMarginLeft = 0;
            this.bunifuButton4.ColorContrastOnClick = 45;
            this.bunifuButton4.ColorContrastOnHover = 45;
            this.bunifuButton4.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.bunifuButton4.CustomizableEdges = borderEdges8;
            this.bunifuButton4.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton4.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton4.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton4.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton4.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton4.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton4.IconMarginLeft = 11;
            this.bunifuButton4.IconPadding = 10;
            this.bunifuButton4.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton4.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton4.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton4.IconSize = 25;
            this.bunifuButton4.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton4.IdleBorderRadius = 8;
            this.bunifuButton4.IdleBorderThickness = 1;
            this.bunifuButton4.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton4.IdleIconLeftImage = null;
            this.bunifuButton4.IdleIconRightImage = null;
            this.bunifuButton4.IndicateFocus = true;
            this.bunifuButton4.Location = new System.Drawing.Point(32, 311);
            this.bunifuButton4.Name = "bunifuButton4";
            this.bunifuButton4.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton4.OnDisabledState.BorderRadius = 8;
            this.bunifuButton4.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnDisabledState.BorderThickness = 1;
            this.bunifuButton4.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton4.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton4.OnDisabledState.IconLeftImage = null;
            this.bunifuButton4.OnDisabledState.IconRightImage = null;
            this.bunifuButton4.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.bunifuButton4.onHoverState.BorderRadius = 8;
            this.bunifuButton4.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.onHoverState.BorderThickness = 1;
            this.bunifuButton4.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.bunifuButton4.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.onHoverState.IconLeftImage = null;
            this.bunifuButton4.onHoverState.IconRightImage = null;
            this.bunifuButton4.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton4.OnIdleState.BorderRadius = 8;
            this.bunifuButton4.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnIdleState.BorderThickness = 1;
            this.bunifuButton4.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton4.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnIdleState.IconLeftImage = null;
            this.bunifuButton4.OnIdleState.IconRightImage = null;
            this.bunifuButton4.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.bunifuButton4.OnPressedState.BorderRadius = 8;
            this.bunifuButton4.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton4.OnPressedState.BorderThickness = 1;
            this.bunifuButton4.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.bunifuButton4.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton4.OnPressedState.IconLeftImage = null;
            this.bunifuButton4.OnPressedState.IconRightImage = null;
            this.bunifuButton4.Size = new System.Drawing.Size(219, 45);
            this.bunifuButton4.TabIndex = 4;
            this.bunifuButton4.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton4.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton4.TextMarginLeft = 0;
            this.bunifuButton4.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton4.UseDefaultRadiusAndThickness = true;
            this.bunifuButton4.Click += new System.EventHandler(this.bunifuButton4_Click);
            // 
            // readerBT
            // 
            this.readerBT.AllowAnimations = true;
            this.readerBT.AllowMouseEffects = true;
            this.readerBT.AllowToggling = true;
            this.readerBT.AnimationSpeed = 200;
            this.readerBT.AutoGenerateColors = false;
            this.readerBT.AutoRoundBorders = false;
            this.readerBT.AutoSizeLeftIcon = true;
            this.readerBT.AutoSizeRightIcon = true;
            this.readerBT.BackColor = System.Drawing.Color.Transparent;
            this.readerBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.readerBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("readerBT.BackgroundImage")));
            this.readerBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.readerBT.ButtonText = "Quản lí đọc giả";
            this.readerBT.ButtonTextMarginLeft = 0;
            this.readerBT.ColorContrastOnClick = 45;
            this.readerBT.ColorContrastOnHover = 45;
            this.readerBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.readerBT.CustomizableEdges = borderEdges9;
            this.readerBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.readerBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.readerBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.readerBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.readerBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.readerBT.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.readerBT.ForeColor = System.Drawing.Color.White;
            this.readerBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.readerBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.readerBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.readerBT.IconMarginLeft = 11;
            this.readerBT.IconPadding = 10;
            this.readerBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.readerBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.readerBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.readerBT.IconSize = 25;
            this.readerBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.readerBT.IdleBorderRadius = 8;
            this.readerBT.IdleBorderThickness = 1;
            this.readerBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.readerBT.IdleIconLeftImage = null;
            this.readerBT.IdleIconRightImage = null;
            this.readerBT.IndicateFocus = true;
            this.readerBT.Location = new System.Drawing.Point(32, 260);
            this.readerBT.Name = "readerBT";
            this.readerBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.readerBT.OnDisabledState.BorderRadius = 8;
            this.readerBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.readerBT.OnDisabledState.BorderThickness = 1;
            this.readerBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.readerBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.readerBT.OnDisabledState.IconLeftImage = null;
            this.readerBT.OnDisabledState.IconRightImage = null;
            this.readerBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.readerBT.onHoverState.BorderRadius = 8;
            this.readerBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.readerBT.onHoverState.BorderThickness = 1;
            this.readerBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.readerBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.readerBT.onHoverState.IconLeftImage = null;
            this.readerBT.onHoverState.IconRightImage = null;
            this.readerBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.readerBT.OnIdleState.BorderRadius = 8;
            this.readerBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.readerBT.OnIdleState.BorderThickness = 1;
            this.readerBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.readerBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.readerBT.OnIdleState.IconLeftImage = null;
            this.readerBT.OnIdleState.IconRightImage = null;
            this.readerBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.readerBT.OnPressedState.BorderRadius = 8;
            this.readerBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.readerBT.OnPressedState.BorderThickness = 1;
            this.readerBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.readerBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.readerBT.OnPressedState.IconLeftImage = null;
            this.readerBT.OnPressedState.IconRightImage = null;
            this.readerBT.Size = new System.Drawing.Size(219, 45);
            this.readerBT.TabIndex = 3;
            this.readerBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.readerBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.readerBT.TextMarginLeft = 0;
            this.readerBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.readerBT.UseDefaultRadiusAndThickness = true;
            this.readerBT.Click += new System.EventHandler(this.readerBT_Click);
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowAnimations = true;
            this.bunifuButton2.AllowMouseEffects = true;
            this.bunifuButton2.AllowToggling = true;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoRoundBorders = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "Quản lí đầu sách";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges10.BottomLeft = true;
            borderEdges10.BottomRight = true;
            borderEdges10.TopLeft = true;
            borderEdges10.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges10;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton2.IdleBorderRadius = 8;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = true;
            this.bunifuButton2.Location = new System.Drawing.Point(32, 158);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 8;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.bunifuButton2.onHoverState.BorderRadius = 8;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnIdleState.BorderRadius = 8;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 8;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(219, 45);
            this.bunifuButton2.TabIndex = 2;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // profileBT
            // 
            this.profileBT.AllowAnimations = true;
            this.profileBT.AllowMouseEffects = true;
            this.profileBT.AllowToggling = true;
            this.profileBT.AnimationSpeed = 200;
            this.profileBT.AutoGenerateColors = false;
            this.profileBT.AutoRoundBorders = false;
            this.profileBT.AutoSizeLeftIcon = true;
            this.profileBT.AutoSizeRightIcon = true;
            this.profileBT.BackColor = System.Drawing.Color.Transparent;
            this.profileBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.profileBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("profileBT.BackgroundImage")));
            this.profileBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.profileBT.ButtonText = "Hồ sơ";
            this.profileBT.ButtonTextMarginLeft = 0;
            this.profileBT.ColorContrastOnClick = 45;
            this.profileBT.ColorContrastOnHover = 45;
            this.profileBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges11.BottomLeft = true;
            borderEdges11.BottomRight = true;
            borderEdges11.TopLeft = true;
            borderEdges11.TopRight = true;
            this.profileBT.CustomizableEdges = borderEdges11;
            this.profileBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.profileBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.profileBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.profileBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.profileBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.profileBT.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.profileBT.ForeColor = System.Drawing.Color.White;
            this.profileBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.profileBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.profileBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.profileBT.IconMarginLeft = 11;
            this.profileBT.IconPadding = 10;
            this.profileBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.profileBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.profileBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.profileBT.IconSize = 25;
            this.profileBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.profileBT.IdleBorderRadius = 8;
            this.profileBT.IdleBorderThickness = 1;
            this.profileBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.profileBT.IdleIconLeftImage = null;
            this.profileBT.IdleIconRightImage = null;
            this.profileBT.IndicateFocus = true;
            this.profileBT.Location = new System.Drawing.Point(32, 107);
            this.profileBT.Name = "profileBT";
            this.profileBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.profileBT.OnDisabledState.BorderRadius = 8;
            this.profileBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.profileBT.OnDisabledState.BorderThickness = 1;
            this.profileBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.profileBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.profileBT.OnDisabledState.IconLeftImage = null;
            this.profileBT.OnDisabledState.IconRightImage = null;
            this.profileBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.profileBT.onHoverState.BorderRadius = 8;
            this.profileBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.profileBT.onHoverState.BorderThickness = 1;
            this.profileBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.profileBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.profileBT.onHoverState.IconLeftImage = null;
            this.profileBT.onHoverState.IconRightImage = null;
            this.profileBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.profileBT.OnIdleState.BorderRadius = 8;
            this.profileBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.profileBT.OnIdleState.BorderThickness = 1;
            this.profileBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.profileBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.profileBT.OnIdleState.IconLeftImage = null;
            this.profileBT.OnIdleState.IconRightImage = null;
            this.profileBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.profileBT.OnPressedState.BorderRadius = 8;
            this.profileBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.profileBT.OnPressedState.BorderThickness = 1;
            this.profileBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.profileBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.profileBT.OnPressedState.IconLeftImage = null;
            this.profileBT.OnPressedState.IconRightImage = null;
            this.profileBT.Size = new System.Drawing.Size(219, 45);
            this.profileBT.TabIndex = 1;
            this.profileBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.profileBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.profileBT.TextMarginLeft = 0;
            this.profileBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.profileBT.UseDefaultRadiusAndThickness = true;
            this.profileBT.Click += new System.EventHandler(this.bunifuButton1_Click);
            // 
            // panel2
            // 
            this.panel2.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.panel2.Controls.Add(this.panel3);
            this.panel2.Controls.Add(this.label1);
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Margin = new System.Windows.Forms.Padding(2);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(287, 102);
            this.panel2.TabIndex = 1;
            // 
            // panel3
            // 
            this.panel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panel3.BackgroundImage")));
            this.panel3.Location = new System.Drawing.Point(46, 31);
            this.panel3.Margin = new System.Windows.Forms.Padding(2);
            this.panel3.Name = "panel3";
            this.panel3.Size = new System.Drawing.Size(50, 50);
            this.panel3.TabIndex = 2;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(100, 44);
            this.label1.Margin = new System.Windows.Forms.Padding(2, 0, 2, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(146, 24);
            this.label1.TabIndex = 1;
            this.label1.Text = "Quản lý thư viện";
            // 
            // contentPanel
            // 
            this.contentPanel.BackColor = System.Drawing.Color.White;
            this.contentPanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.contentPanel.Location = new System.Drawing.Point(287, 0);
            this.contentPanel.Name = "contentPanel";
            this.contentPanel.Size = new System.Drawing.Size(1022, 763);
            this.contentPanel.TabIndex = 1;
            // 
            // MainForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1309, 763);
            this.Controls.Add(this.contentPanel);
            this.Controls.Add(this.panel1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "MainForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Quản lý thư viện";
            this.Shown += new System.EventHandler(this.MainForm_Shown);
            this.panel1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton profileBT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton4;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton readerBT;
        private System.Windows.Forms.Panel contentPanel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton authorBT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bookBT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton lendingSlipBT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton simulationBT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton libraryCardBT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton liquidatingSlipBT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton logoutBT;
    }
}