namespace QuanLyThuVien.Forms.LibrarianFroms
{
    partial class DetailForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DetailForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties65 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties66 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties67 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties68 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties69 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties70 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties71 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties72 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties73 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties74 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties75 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties76 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties77 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties78 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties79 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties80 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties81 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties82 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties83 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties84 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties85 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties86 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties87 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties88 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties89 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties90 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties91 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties92 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties93 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties94 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties95 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties96 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.firstNameTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.iDTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.lastNameTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.addressTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.emailTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.sexDD = new Bunifu.UI.WinForms.BunifuDropdown();
            this.birthdayDP = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.accountTP = new System.Windows.Forms.TabPage();
            this.changePasswordLB = new System.Windows.Forms.Label();
            this.changePasswordCB = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.label8 = new System.Windows.Forms.Label();
            this.enableCB = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.usernameTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label14 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.passwordCfTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.passwordTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.closeBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.saveBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.accountTP.SuspendLayout();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.accountTP);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 0);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(397, 482);
            this.tabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.BackColor = System.Drawing.Color.White;
            this.tabPage1.Controls.Add(this.firstNameTB);
            this.tabPage1.Controls.Add(this.label1);
            this.tabPage1.Controls.Add(this.iDTB);
            this.tabPage1.Controls.Add(this.label2);
            this.tabPage1.Controls.Add(this.lastNameTB);
            this.tabPage1.Controls.Add(this.label3);
            this.tabPage1.Controls.Add(this.label4);
            this.tabPage1.Controls.Add(this.label5);
            this.tabPage1.Controls.Add(this.label6);
            this.tabPage1.Controls.Add(this.addressTB);
            this.tabPage1.Controls.Add(this.label7);
            this.tabPage1.Controls.Add(this.emailTB);
            this.tabPage1.Controls.Add(this.sexDD);
            this.tabPage1.Controls.Add(this.birthdayDP);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(389, 456);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Thông tin";
            // 
            // firstNameTB
            // 
            this.firstNameTB.AcceptsReturn = false;
            this.firstNameTB.AcceptsTab = false;
            this.firstNameTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.firstNameTB.AnimationSpeed = 200;
            this.firstNameTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.firstNameTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.firstNameTB.BackColor = System.Drawing.Color.Transparent;
            this.firstNameTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("firstNameTB.BackgroundImage")));
            this.firstNameTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.firstNameTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.firstNameTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.firstNameTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.firstNameTB.BorderRadius = 8;
            this.firstNameTB.BorderThickness = 1;
            this.firstNameTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.firstNameTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNameTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.firstNameTB.DefaultText = "";
            this.firstNameTB.FillColor = System.Drawing.Color.White;
            this.firstNameTB.HideSelection = true;
            this.firstNameTB.IconLeft = null;
            this.firstNameTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNameTB.IconPadding = 10;
            this.firstNameTB.IconRight = null;
            this.firstNameTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNameTB.Lines = new string[0];
            this.firstNameTB.Location = new System.Drawing.Point(121, 92);
            this.firstNameTB.MaxLength = 32767;
            this.firstNameTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.firstNameTB.Modified = false;
            this.firstNameTB.Multiline = false;
            this.firstNameTB.Name = "firstNameTB";
            stateProperties65.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties65.FillColor = System.Drawing.Color.Empty;
            stateProperties65.ForeColor = System.Drawing.Color.Empty;
            stateProperties65.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameTB.OnActiveState = stateProperties65;
            stateProperties66.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties66.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties66.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties66.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.firstNameTB.OnDisabledState = stateProperties66;
            stateProperties67.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties67.FillColor = System.Drawing.Color.Empty;
            stateProperties67.ForeColor = System.Drawing.Color.Empty;
            stateProperties67.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameTB.OnHoverState = stateProperties67;
            stateProperties68.BorderColor = System.Drawing.Color.Silver;
            stateProperties68.FillColor = System.Drawing.Color.White;
            stateProperties68.ForeColor = System.Drawing.Color.Empty;
            stateProperties68.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameTB.OnIdleState = stateProperties68;
            this.firstNameTB.Padding = new System.Windows.Forms.Padding(3);
            this.firstNameTB.PasswordChar = '\0';
            this.firstNameTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.firstNameTB.PlaceholderText = "Enter text";
            this.firstNameTB.ReadOnly = false;
            this.firstNameTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.firstNameTB.SelectedText = "";
            this.firstNameTB.SelectionLength = 0;
            this.firstNameTB.SelectionStart = 0;
            this.firstNameTB.ShortcutsEnabled = true;
            this.firstNameTB.Size = new System.Drawing.Size(260, 37);
            this.firstNameTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.firstNameTB.TabIndex = 35;
            this.firstNameTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.firstNameTB.TextMarginBottom = 0;
            this.firstNameTB.TextMarginLeft = 3;
            this.firstNameTB.TextMarginTop = 0;
            this.firstNameTB.TextPlaceholder = "Enter text";
            this.firstNameTB.UseSystemPasswordChar = false;
            this.firstNameTB.WordWrap = true;
            // 
            // label1
            // 
            this.label1.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.label1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label1.AutoSize = true;
            this.label1.Cursor = System.Windows.Forms.Cursors.Default;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(96, 28);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(19, 15);
            this.label1.TabIndex = 30;
            this.label1.Text = "ID";
            // 
            // iDTB
            // 
            this.iDTB.AcceptsReturn = false;
            this.iDTB.AcceptsTab = false;
            this.iDTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.iDTB.AnimationSpeed = 200;
            this.iDTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.iDTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.iDTB.BackColor = System.Drawing.Color.Transparent;
            this.iDTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("iDTB.BackgroundImage")));
            this.iDTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.iDTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.iDTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.iDTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.iDTB.BorderRadius = 8;
            this.iDTB.BorderThickness = 1;
            this.iDTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.iDTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.iDTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.iDTB.DefaultText = "";
            this.iDTB.Enabled = false;
            this.iDTB.FillColor = System.Drawing.Color.White;
            this.iDTB.HideSelection = true;
            this.iDTB.IconLeft = null;
            this.iDTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.iDTB.IconPadding = 10;
            this.iDTB.IconRight = null;
            this.iDTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.iDTB.Lines = new string[0];
            this.iDTB.Location = new System.Drawing.Point(121, 6);
            this.iDTB.MaxLength = 32767;
            this.iDTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.iDTB.Modified = false;
            this.iDTB.Multiline = false;
            this.iDTB.Name = "iDTB";
            stateProperties69.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties69.FillColor = System.Drawing.Color.Empty;
            stateProperties69.ForeColor = System.Drawing.Color.Empty;
            stateProperties69.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.iDTB.OnActiveState = stateProperties69;
            stateProperties70.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties70.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties70.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties70.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.iDTB.OnDisabledState = stateProperties70;
            stateProperties71.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties71.FillColor = System.Drawing.Color.Empty;
            stateProperties71.ForeColor = System.Drawing.Color.Empty;
            stateProperties71.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.iDTB.OnHoverState = stateProperties71;
            stateProperties72.BorderColor = System.Drawing.Color.Silver;
            stateProperties72.FillColor = System.Drawing.Color.White;
            stateProperties72.ForeColor = System.Drawing.Color.Empty;
            stateProperties72.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.iDTB.OnIdleState = stateProperties72;
            this.iDTB.Padding = new System.Windows.Forms.Padding(3);
            this.iDTB.PasswordChar = '\0';
            this.iDTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.iDTB.PlaceholderText = "Enter text";
            this.iDTB.ReadOnly = false;
            this.iDTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.iDTB.SelectedText = "";
            this.iDTB.SelectionLength = 0;
            this.iDTB.SelectionStart = 0;
            this.iDTB.ShortcutsEnabled = true;
            this.iDTB.Size = new System.Drawing.Size(260, 37);
            this.iDTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.iDTB.TabIndex = 31;
            this.iDTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.iDTB.TextMarginBottom = 0;
            this.iDTB.TextMarginLeft = 3;
            this.iDTB.TextMarginTop = 0;
            this.iDTB.TextPlaceholder = "Enter text";
            this.iDTB.UseSystemPasswordChar = false;
            this.iDTB.WordWrap = true;
            // 
            // label2
            // 
            this.label2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(92, 71);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(23, 15);
            this.label2.TabIndex = 32;
            this.label2.Text = "Họ";
            // 
            // lastNameTB
            // 
            this.lastNameTB.AcceptsReturn = false;
            this.lastNameTB.AcceptsTab = false;
            this.lastNameTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lastNameTB.AnimationSpeed = 200;
            this.lastNameTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lastNameTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lastNameTB.BackColor = System.Drawing.Color.Transparent;
            this.lastNameTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lastNameTB.BackgroundImage")));
            this.lastNameTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.lastNameTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lastNameTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.lastNameTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.lastNameTB.BorderRadius = 8;
            this.lastNameTB.BorderThickness = 1;
            this.lastNameTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lastNameTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.lastNameTB.DefaultText = "";
            this.lastNameTB.FillColor = System.Drawing.Color.White;
            this.lastNameTB.HideSelection = true;
            this.lastNameTB.IconLeft = null;
            this.lastNameTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTB.IconPadding = 10;
            this.lastNameTB.IconRight = null;
            this.lastNameTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTB.Lines = new string[0];
            this.lastNameTB.Location = new System.Drawing.Point(121, 49);
            this.lastNameTB.MaxLength = 32767;
            this.lastNameTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.lastNameTB.Modified = false;
            this.lastNameTB.Multiline = false;
            this.lastNameTB.Name = "lastNameTB";
            stateProperties73.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties73.FillColor = System.Drawing.Color.Empty;
            stateProperties73.ForeColor = System.Drawing.Color.Empty;
            stateProperties73.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTB.OnActiveState = stateProperties73;
            stateProperties74.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties74.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties74.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties74.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lastNameTB.OnDisabledState = stateProperties74;
            stateProperties75.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties75.FillColor = System.Drawing.Color.Empty;
            stateProperties75.ForeColor = System.Drawing.Color.Empty;
            stateProperties75.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTB.OnHoverState = stateProperties75;
            stateProperties76.BorderColor = System.Drawing.Color.Silver;
            stateProperties76.FillColor = System.Drawing.Color.White;
            stateProperties76.ForeColor = System.Drawing.Color.Empty;
            stateProperties76.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTB.OnIdleState = stateProperties76;
            this.lastNameTB.Padding = new System.Windows.Forms.Padding(3);
            this.lastNameTB.PasswordChar = '\0';
            this.lastNameTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lastNameTB.PlaceholderText = "Enter text";
            this.lastNameTB.ReadOnly = false;
            this.lastNameTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lastNameTB.SelectedText = "";
            this.lastNameTB.SelectionLength = 0;
            this.lastNameTB.SelectionStart = 0;
            this.lastNameTB.ShortcutsEnabled = true;
            this.lastNameTB.Size = new System.Drawing.Size(260, 37);
            this.lastNameTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lastNameTB.TabIndex = 33;
            this.lastNameTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lastNameTB.TextMarginBottom = 0;
            this.lastNameTB.TextMarginLeft = 3;
            this.lastNameTB.TextMarginTop = 0;
            this.lastNameTB.TextPlaceholder = "Enter text";
            this.lastNameTB.UseSystemPasswordChar = false;
            this.lastNameTB.WordWrap = true;
            // 
            // label3
            // 
            this.label3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(87, 114);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(28, 15);
            this.label3.TabIndex = 34;
            this.label3.Text = "Tên";
            // 
            // label4
            // 
            this.label4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(63, 152);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(52, 15);
            this.label4.TabIndex = 36;
            this.label4.Text = "Giới tính";
            // 
            // label5
            // 
            this.label5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(56, 190);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(59, 15);
            this.label5.TabIndex = 37;
            this.label5.Text = "Sinh nhật";
            // 
            // label6
            // 
            this.label6.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(76, 233);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(39, 15);
            this.label6.TabIndex = 38;
            this.label6.Text = "Email";
            // 
            // addressTB
            // 
            this.addressTB.AcceptsReturn = false;
            this.addressTB.AcceptsTab = false;
            this.addressTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.addressTB.AnimationSpeed = 200;
            this.addressTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addressTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addressTB.BackColor = System.Drawing.Color.Transparent;
            this.addressTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addressTB.BackgroundImage")));
            this.addressTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.addressTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addressTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.addressTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.addressTB.BorderRadius = 8;
            this.addressTB.BorderThickness = 1;
            this.addressTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addressTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addressTB.DefaultText = "";
            this.addressTB.FillColor = System.Drawing.Color.White;
            this.addressTB.HideSelection = true;
            this.addressTB.IconLeft = null;
            this.addressTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTB.IconPadding = 10;
            this.addressTB.IconRight = null;
            this.addressTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTB.Lines = new string[0];
            this.addressTB.Location = new System.Drawing.Point(121, 254);
            this.addressTB.MaxLength = 32767;
            this.addressTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.addressTB.Modified = false;
            this.addressTB.Multiline = false;
            this.addressTB.Name = "addressTB";
            stateProperties77.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties77.FillColor = System.Drawing.Color.Empty;
            stateProperties77.ForeColor = System.Drawing.Color.Empty;
            stateProperties77.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTB.OnActiveState = stateProperties77;
            stateProperties78.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties78.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties78.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties78.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addressTB.OnDisabledState = stateProperties78;
            stateProperties79.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties79.FillColor = System.Drawing.Color.Empty;
            stateProperties79.ForeColor = System.Drawing.Color.Empty;
            stateProperties79.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTB.OnHoverState = stateProperties79;
            stateProperties80.BorderColor = System.Drawing.Color.Silver;
            stateProperties80.FillColor = System.Drawing.Color.White;
            stateProperties80.ForeColor = System.Drawing.Color.Empty;
            stateProperties80.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTB.OnIdleState = stateProperties80;
            this.addressTB.Padding = new System.Windows.Forms.Padding(3);
            this.addressTB.PasswordChar = '\0';
            this.addressTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressTB.PlaceholderText = "Enter text";
            this.addressTB.ReadOnly = false;
            this.addressTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addressTB.SelectedText = "";
            this.addressTB.SelectionLength = 0;
            this.addressTB.SelectionStart = 0;
            this.addressTB.ShortcutsEnabled = true;
            this.addressTB.Size = new System.Drawing.Size(260, 37);
            this.addressTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addressTB.TabIndex = 43;
            this.addressTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addressTB.TextMarginBottom = 0;
            this.addressTB.TextMarginLeft = 3;
            this.addressTB.TextMarginTop = 0;
            this.addressTB.TextPlaceholder = "Enter text";
            this.addressTB.UseSystemPasswordChar = false;
            this.addressTB.WordWrap = true;
            // 
            // label7
            // 
            this.label7.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(70, 276);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(45, 15);
            this.label7.TabIndex = 39;
            this.label7.Text = "Địa chỉ";
            // 
            // emailTB
            // 
            this.emailTB.AcceptsReturn = false;
            this.emailTB.AcceptsTab = false;
            this.emailTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.emailTB.AnimationSpeed = 200;
            this.emailTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailTB.BackColor = System.Drawing.Color.Transparent;
            this.emailTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailTB.BackgroundImage")));
            this.emailTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.emailTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.emailTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.emailTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.emailTB.BorderRadius = 8;
            this.emailTB.BorderThickness = 1;
            this.emailTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.emailTB.DefaultText = "";
            this.emailTB.FillColor = System.Drawing.Color.White;
            this.emailTB.HideSelection = true;
            this.emailTB.IconLeft = null;
            this.emailTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailTB.IconPadding = 10;
            this.emailTB.IconRight = null;
            this.emailTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailTB.Lines = new string[0];
            this.emailTB.Location = new System.Drawing.Point(121, 211);
            this.emailTB.MaxLength = 32767;
            this.emailTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailTB.Modified = false;
            this.emailTB.Multiline = false;
            this.emailTB.Name = "emailTB";
            stateProperties81.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties81.FillColor = System.Drawing.Color.Empty;
            stateProperties81.ForeColor = System.Drawing.Color.Empty;
            stateProperties81.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailTB.OnActiveState = stateProperties81;
            stateProperties82.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties82.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties82.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties82.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailTB.OnDisabledState = stateProperties82;
            stateProperties83.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties83.FillColor = System.Drawing.Color.Empty;
            stateProperties83.ForeColor = System.Drawing.Color.Empty;
            stateProperties83.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailTB.OnHoverState = stateProperties83;
            stateProperties84.BorderColor = System.Drawing.Color.Silver;
            stateProperties84.FillColor = System.Drawing.Color.White;
            stateProperties84.ForeColor = System.Drawing.Color.Empty;
            stateProperties84.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailTB.OnIdleState = stateProperties84;
            this.emailTB.Padding = new System.Windows.Forms.Padding(3);
            this.emailTB.PasswordChar = '\0';
            this.emailTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.emailTB.PlaceholderText = "Enter text";
            this.emailTB.ReadOnly = false;
            this.emailTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailTB.SelectedText = "";
            this.emailTB.SelectionLength = 0;
            this.emailTB.SelectionStart = 0;
            this.emailTB.ShortcutsEnabled = true;
            this.emailTB.Size = new System.Drawing.Size(260, 37);
            this.emailTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailTB.TabIndex = 42;
            this.emailTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.emailTB.TextMarginBottom = 0;
            this.emailTB.TextMarginLeft = 3;
            this.emailTB.TextMarginTop = 0;
            this.emailTB.TextPlaceholder = "Enter text";
            this.emailTB.UseSystemPasswordChar = false;
            this.emailTB.WordWrap = true;
            // 
            // sexDD
            // 
            this.sexDD.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.sexDD.BackColor = System.Drawing.Color.Transparent;
            this.sexDD.BackgroundColor = System.Drawing.Color.White;
            this.sexDD.BorderColor = System.Drawing.Color.Silver;
            this.sexDD.BorderRadius = 8;
            this.sexDD.Color = System.Drawing.Color.Silver;
            this.sexDD.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.sexDD.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.sexDD.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sexDD.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.sexDD.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.sexDD.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.sexDD.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.sexDD.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.sexDD.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.sexDD.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.sexDD.FillDropDown = true;
            this.sexDD.FillIndicator = false;
            this.sexDD.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.sexDD.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.sexDD.ForeColor = System.Drawing.Color.Black;
            this.sexDD.FormattingEnabled = true;
            this.sexDD.Icon = null;
            this.sexDD.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.sexDD.IndicatorColor = System.Drawing.Color.Gray;
            this.sexDD.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.sexDD.ItemBackColor = System.Drawing.Color.White;
            this.sexDD.ItemBorderColor = System.Drawing.Color.White;
            this.sexDD.ItemForeColor = System.Drawing.Color.Black;
            this.sexDD.ItemHeight = 26;
            this.sexDD.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.sexDD.ItemHighLightForeColor = System.Drawing.Color.White;
            this.sexDD.ItemTopMargin = 3;
            this.sexDD.Location = new System.Drawing.Point(121, 135);
            this.sexDD.Name = "sexDD";
            this.sexDD.Size = new System.Drawing.Size(260, 32);
            this.sexDD.TabIndex = 40;
            this.sexDD.Text = null;
            this.sexDD.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.sexDD.TextLeftMargin = 5;
            // 
            // birthdayDP
            // 
            this.birthdayDP.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.birthdayDP.BackColor = System.Drawing.Color.Transparent;
            this.birthdayDP.BorderRadius = 8;
            this.birthdayDP.Color = System.Drawing.Color.Silver;
            this.birthdayDP.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.birthdayDP.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.birthdayDP.DisabledColor = System.Drawing.Color.Gray;
            this.birthdayDP.DisplayWeekNumbers = false;
            this.birthdayDP.DPHeight = 0;
            this.birthdayDP.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.birthdayDP.FillDatePicker = false;
            this.birthdayDP.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.birthdayDP.ForeColor = System.Drawing.Color.Black;
            this.birthdayDP.Icon = ((System.Drawing.Image)(resources.GetObject("birthdayDP.Icon")));
            this.birthdayDP.IconColor = System.Drawing.Color.Gray;
            this.birthdayDP.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.birthdayDP.LeftTextMargin = 5;
            this.birthdayDP.Location = new System.Drawing.Point(121, 173);
            this.birthdayDP.MinimumSize = new System.Drawing.Size(4, 32);
            this.birthdayDP.Name = "birthdayDP";
            this.birthdayDP.Size = new System.Drawing.Size(260, 32);
            this.birthdayDP.TabIndex = 41;
            // 
            // accountTP
            // 
            this.accountTP.BackColor = System.Drawing.Color.White;
            this.accountTP.Controls.Add(this.changePasswordLB);
            this.accountTP.Controls.Add(this.changePasswordCB);
            this.accountTP.Controls.Add(this.label8);
            this.accountTP.Controls.Add(this.enableCB);
            this.accountTP.Controls.Add(this.usernameTB);
            this.accountTP.Controls.Add(this.label14);
            this.accountTP.Controls.Add(this.label13);
            this.accountTP.Controls.Add(this.passwordCfTB);
            this.accountTP.Controls.Add(this.passwordTB);
            this.accountTP.Controls.Add(this.label12);
            this.accountTP.Location = new System.Drawing.Point(4, 22);
            this.accountTP.Name = "accountTP";
            this.accountTP.Padding = new System.Windows.Forms.Padding(3);
            this.accountTP.Size = new System.Drawing.Size(389, 456);
            this.accountTP.TabIndex = 1;
            this.accountTP.Text = "Tài khoản";
            // 
            // changePasswordLB
            // 
            this.changePasswordLB.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.changePasswordLB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.changePasswordLB.AutoSize = true;
            this.changePasswordLB.Cursor = System.Windows.Forms.Cursors.Default;
            this.changePasswordLB.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.changePasswordLB.Location = new System.Drawing.Point(274, 342);
            this.changePasswordLB.Name = "changePasswordLB";
            this.changePasswordLB.Size = new System.Drawing.Size(109, 15);
            this.changePasswordLB.TabIndex = 49;
            this.changePasswordLB.Text = "Cập nhật tài khoản";
            // 
            // changePasswordCB
            // 
            this.changePasswordCB.AllowBindingControlAnimation = true;
            this.changePasswordCB.AllowBindingControlColorChanges = false;
            this.changePasswordCB.AllowBindingControlLocation = true;
            this.changePasswordCB.AllowCheckBoxAnimation = false;
            this.changePasswordCB.AllowCheckmarkAnimation = true;
            this.changePasswordCB.AllowOnHoverStates = true;
            this.changePasswordCB.AutoCheck = true;
            this.changePasswordCB.BackColor = System.Drawing.Color.Transparent;
            this.changePasswordCB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("changePasswordCB.BackgroundImage")));
            this.changePasswordCB.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.changePasswordCB.BindingControl = this.changePasswordLB;
            this.changePasswordCB.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.changePasswordCB.BorderRadius = 12;
            this.changePasswordCB.Checked = false;
            this.changePasswordCB.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.changePasswordCB.Cursor = System.Windows.Forms.Cursors.Default;
            this.changePasswordCB.CustomCheckmarkImage = null;
            this.changePasswordCB.Location = new System.Drawing.Point(250, 338);
            this.changePasswordCB.MinimumSize = new System.Drawing.Size(17, 17);
            this.changePasswordCB.Name = "changePasswordCB";
            this.changePasswordCB.OnCheck.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.changePasswordCB.OnCheck.BorderRadius = 12;
            this.changePasswordCB.OnCheck.BorderThickness = 2;
            this.changePasswordCB.OnCheck.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.changePasswordCB.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.changePasswordCB.OnCheck.CheckmarkThickness = 2;
            this.changePasswordCB.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.changePasswordCB.OnDisable.BorderRadius = 12;
            this.changePasswordCB.OnDisable.BorderThickness = 2;
            this.changePasswordCB.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.changePasswordCB.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.changePasswordCB.OnDisable.CheckmarkThickness = 2;
            this.changePasswordCB.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.changePasswordCB.OnHoverChecked.BorderRadius = 12;
            this.changePasswordCB.OnHoverChecked.BorderThickness = 2;
            this.changePasswordCB.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.changePasswordCB.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.changePasswordCB.OnHoverChecked.CheckmarkThickness = 2;
            this.changePasswordCB.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.changePasswordCB.OnHoverUnchecked.BorderRadius = 12;
            this.changePasswordCB.OnHoverUnchecked.BorderThickness = 1;
            this.changePasswordCB.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.changePasswordCB.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.changePasswordCB.OnUncheck.BorderRadius = 12;
            this.changePasswordCB.OnUncheck.BorderThickness = 1;
            this.changePasswordCB.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.changePasswordCB.Size = new System.Drawing.Size(21, 21);
            this.changePasswordCB.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.changePasswordCB.TabIndex = 45;
            this.changePasswordCB.ThreeState = false;
            this.changePasswordCB.ToolTipText = null;
            this.changePasswordCB.CheckedChanged += new System.EventHandler<Bunifu.UI.WinForms.BunifuCheckBox.CheckedChangedEventArgs>(this.changePasswordCB_CheckedChanged);
            // 
            // label8
            // 
            this.label8.AccessibleRole = System.Windows.Forms.AccessibleRole.CheckButton;
            this.label8.AutoSize = true;
            this.label8.Cursor = System.Windows.Forms.Cursors.Default;
            this.label8.Location = new System.Drawing.Point(145, 155);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(58, 13);
            this.label8.TabIndex = 44;
            this.label8.Text = "Hoạt động";
            // 
            // enableCB
            // 
            this.enableCB.AllowBindingControlAnimation = true;
            this.enableCB.AllowBindingControlColorChanges = false;
            this.enableCB.AllowBindingControlLocation = true;
            this.enableCB.AllowCheckBoxAnimation = false;
            this.enableCB.AllowCheckmarkAnimation = true;
            this.enableCB.AllowOnHoverStates = true;
            this.enableCB.AutoCheck = true;
            this.enableCB.BackColor = System.Drawing.Color.Transparent;
            this.enableCB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("enableCB.BackgroundImage")));
            this.enableCB.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.enableCB.BindingControl = this.label8;
            this.enableCB.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.enableCB.BorderRadius = 12;
            this.enableCB.Checked = true;
            this.enableCB.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Checked;
            this.enableCB.Cursor = System.Windows.Forms.Cursors.Default;
            this.enableCB.CustomCheckmarkImage = null;
            this.enableCB.Location = new System.Drawing.Point(121, 151);
            this.enableCB.MinimumSize = new System.Drawing.Size(17, 17);
            this.enableCB.Name = "enableCB";
            this.enableCB.OnCheck.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.enableCB.OnCheck.BorderRadius = 12;
            this.enableCB.OnCheck.BorderThickness = 2;
            this.enableCB.OnCheck.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.enableCB.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.enableCB.OnCheck.CheckmarkThickness = 2;
            this.enableCB.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.enableCB.OnDisable.BorderRadius = 12;
            this.enableCB.OnDisable.BorderThickness = 2;
            this.enableCB.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.enableCB.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.enableCB.OnDisable.CheckmarkThickness = 2;
            this.enableCB.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.enableCB.OnHoverChecked.BorderRadius = 12;
            this.enableCB.OnHoverChecked.BorderThickness = 2;
            this.enableCB.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.enableCB.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.enableCB.OnHoverChecked.CheckmarkThickness = 2;
            this.enableCB.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.enableCB.OnHoverUnchecked.BorderRadius = 12;
            this.enableCB.OnHoverUnchecked.BorderThickness = 1;
            this.enableCB.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.enableCB.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.enableCB.OnUncheck.BorderRadius = 12;
            this.enableCB.OnUncheck.BorderThickness = 1;
            this.enableCB.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.enableCB.Size = new System.Drawing.Size(21, 21);
            this.enableCB.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.enableCB.TabIndex = 43;
            this.enableCB.ThreeState = false;
            this.enableCB.ToolTipText = null;
            // 
            // usernameTB
            // 
            this.usernameTB.AcceptsReturn = false;
            this.usernameTB.AcceptsTab = false;
            this.usernameTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.usernameTB.AnimationSpeed = 200;
            this.usernameTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.usernameTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.usernameTB.BackColor = System.Drawing.Color.Transparent;
            this.usernameTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("usernameTB.BackgroundImage")));
            this.usernameTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.usernameTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.usernameTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.usernameTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.usernameTB.BorderRadius = 8;
            this.usernameTB.BorderThickness = 1;
            this.usernameTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.usernameTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.usernameTB.DefaultText = "";
            this.usernameTB.FillColor = System.Drawing.Color.White;
            this.usernameTB.HideSelection = true;
            this.usernameTB.IconLeft = null;
            this.usernameTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTB.IconPadding = 10;
            this.usernameTB.IconRight = null;
            this.usernameTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTB.Lines = new string[0];
            this.usernameTB.Location = new System.Drawing.Point(121, 6);
            this.usernameTB.MaxLength = 32767;
            this.usernameTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.usernameTB.Modified = false;
            this.usernameTB.Multiline = false;
            this.usernameTB.Name = "usernameTB";
            stateProperties85.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties85.FillColor = System.Drawing.Color.Empty;
            stateProperties85.ForeColor = System.Drawing.Color.Empty;
            stateProperties85.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTB.OnActiveState = stateProperties85;
            stateProperties86.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties86.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties86.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties86.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.usernameTB.OnDisabledState = stateProperties86;
            stateProperties87.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties87.FillColor = System.Drawing.Color.Empty;
            stateProperties87.ForeColor = System.Drawing.Color.Empty;
            stateProperties87.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTB.OnHoverState = stateProperties87;
            stateProperties88.BorderColor = System.Drawing.Color.Silver;
            stateProperties88.FillColor = System.Drawing.Color.White;
            stateProperties88.ForeColor = System.Drawing.Color.Empty;
            stateProperties88.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTB.OnIdleState = stateProperties88;
            this.usernameTB.Padding = new System.Windows.Forms.Padding(3);
            this.usernameTB.PasswordChar = '\0';
            this.usernameTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.usernameTB.PlaceholderText = "Enter text";
            this.usernameTB.ReadOnly = false;
            this.usernameTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.usernameTB.SelectedText = "";
            this.usernameTB.SelectionLength = 0;
            this.usernameTB.SelectionStart = 0;
            this.usernameTB.ShortcutsEnabled = true;
            this.usernameTB.Size = new System.Drawing.Size(260, 37);
            this.usernameTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.usernameTB.TabIndex = 38;
            this.usernameTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.usernameTB.TextMarginBottom = 0;
            this.usernameTB.TextMarginLeft = 3;
            this.usernameTB.TextMarginTop = 0;
            this.usernameTB.TextPlaceholder = "Enter text";
            this.usernameTB.UseSystemPasswordChar = false;
            this.usernameTB.WordWrap = true;
            // 
            // label14
            // 
            this.label14.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.Location = new System.Drawing.Point(96, 28);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(19, 15);
            this.label14.TabIndex = 37;
            this.label14.Text = "ID";
            // 
            // label13
            // 
            this.label13.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(57, 71);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(58, 15);
            this.label13.TabIndex = 39;
            this.label13.Text = "Mật khẩu";
            // 
            // passwordCfTB
            // 
            this.passwordCfTB.AcceptsReturn = false;
            this.passwordCfTB.AcceptsTab = false;
            this.passwordCfTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.passwordCfTB.AnimationSpeed = 200;
            this.passwordCfTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.passwordCfTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.passwordCfTB.BackColor = System.Drawing.Color.Transparent;
            this.passwordCfTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("passwordCfTB.BackgroundImage")));
            this.passwordCfTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.passwordCfTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.passwordCfTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.passwordCfTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.passwordCfTB.BorderRadius = 8;
            this.passwordCfTB.BorderThickness = 1;
            this.passwordCfTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.passwordCfTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordCfTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.passwordCfTB.DefaultText = "";
            this.passwordCfTB.FillColor = System.Drawing.Color.White;
            this.passwordCfTB.HideSelection = true;
            this.passwordCfTB.IconLeft = null;
            this.passwordCfTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordCfTB.IconPadding = 10;
            this.passwordCfTB.IconRight = null;
            this.passwordCfTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordCfTB.Lines = new string[0];
            this.passwordCfTB.Location = new System.Drawing.Point(121, 92);
            this.passwordCfTB.MaxLength = 32767;
            this.passwordCfTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.passwordCfTB.Modified = false;
            this.passwordCfTB.Multiline = false;
            this.passwordCfTB.Name = "passwordCfTB";
            stateProperties89.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties89.FillColor = System.Drawing.Color.Empty;
            stateProperties89.ForeColor = System.Drawing.Color.Empty;
            stateProperties89.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordCfTB.OnActiveState = stateProperties89;
            stateProperties90.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties90.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties90.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties90.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.passwordCfTB.OnDisabledState = stateProperties90;
            stateProperties91.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties91.FillColor = System.Drawing.Color.Empty;
            stateProperties91.ForeColor = System.Drawing.Color.Empty;
            stateProperties91.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordCfTB.OnHoverState = stateProperties91;
            stateProperties92.BorderColor = System.Drawing.Color.Silver;
            stateProperties92.FillColor = System.Drawing.Color.White;
            stateProperties92.ForeColor = System.Drawing.Color.Empty;
            stateProperties92.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordCfTB.OnIdleState = stateProperties92;
            this.passwordCfTB.Padding = new System.Windows.Forms.Padding(3);
            this.passwordCfTB.PasswordChar = '*';
            this.passwordCfTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.passwordCfTB.PlaceholderText = "Enter text";
            this.passwordCfTB.ReadOnly = false;
            this.passwordCfTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.passwordCfTB.SelectedText = "";
            this.passwordCfTB.SelectionLength = 0;
            this.passwordCfTB.SelectionStart = 0;
            this.passwordCfTB.ShortcutsEnabled = true;
            this.passwordCfTB.Size = new System.Drawing.Size(260, 37);
            this.passwordCfTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.passwordCfTB.TabIndex = 42;
            this.passwordCfTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.passwordCfTB.TextMarginBottom = 0;
            this.passwordCfTB.TextMarginLeft = 3;
            this.passwordCfTB.TextMarginTop = 0;
            this.passwordCfTB.TextPlaceholder = "Enter text";
            this.passwordCfTB.UseSystemPasswordChar = false;
            this.passwordCfTB.WordWrap = true;
            // 
            // passwordTB
            // 
            this.passwordTB.AcceptsReturn = false;
            this.passwordTB.AcceptsTab = false;
            this.passwordTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.passwordTB.AnimationSpeed = 200;
            this.passwordTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.passwordTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.passwordTB.BackColor = System.Drawing.Color.Transparent;
            this.passwordTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("passwordTB.BackgroundImage")));
            this.passwordTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.passwordTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.passwordTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.passwordTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.passwordTB.BorderRadius = 8;
            this.passwordTB.BorderThickness = 1;
            this.passwordTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.passwordTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.passwordTB.DefaultText = "";
            this.passwordTB.FillColor = System.Drawing.Color.White;
            this.passwordTB.HideSelection = true;
            this.passwordTB.IconLeft = null;
            this.passwordTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordTB.IconPadding = 10;
            this.passwordTB.IconRight = null;
            this.passwordTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordTB.Lines = new string[0];
            this.passwordTB.Location = new System.Drawing.Point(121, 49);
            this.passwordTB.MaxLength = 32767;
            this.passwordTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.passwordTB.Modified = false;
            this.passwordTB.Multiline = false;
            this.passwordTB.Name = "passwordTB";
            stateProperties93.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties93.FillColor = System.Drawing.Color.Empty;
            stateProperties93.ForeColor = System.Drawing.Color.Empty;
            stateProperties93.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordTB.OnActiveState = stateProperties93;
            stateProperties94.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties94.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties94.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties94.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.passwordTB.OnDisabledState = stateProperties94;
            stateProperties95.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties95.FillColor = System.Drawing.Color.Empty;
            stateProperties95.ForeColor = System.Drawing.Color.Empty;
            stateProperties95.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordTB.OnHoverState = stateProperties95;
            stateProperties96.BorderColor = System.Drawing.Color.Silver;
            stateProperties96.FillColor = System.Drawing.Color.White;
            stateProperties96.ForeColor = System.Drawing.Color.Empty;
            stateProperties96.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordTB.OnIdleState = stateProperties96;
            this.passwordTB.Padding = new System.Windows.Forms.Padding(3);
            this.passwordTB.PasswordChar = '*';
            this.passwordTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.passwordTB.PlaceholderText = "Enter text";
            this.passwordTB.ReadOnly = false;
            this.passwordTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.passwordTB.SelectedText = "";
            this.passwordTB.SelectionLength = 0;
            this.passwordTB.SelectionStart = 0;
            this.passwordTB.ShortcutsEnabled = true;
            this.passwordTB.Size = new System.Drawing.Size(260, 37);
            this.passwordTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.passwordTB.TabIndex = 40;
            this.passwordTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.passwordTB.TextMarginBottom = 0;
            this.passwordTB.TextMarginLeft = 3;
            this.passwordTB.TextMarginTop = 0;
            this.passwordTB.TextPlaceholder = "Enter text";
            this.passwordTB.UseSystemPasswordChar = false;
            this.passwordTB.WordWrap = true;
            // 
            // label12
            // 
            this.label12.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.Location = new System.Drawing.Point(8, 114);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(107, 15);
            this.label12.TabIndex = 41;
            this.label12.Text = "Nhập lại mật khẩu";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.closeBT);
            this.panel1.Controls.Add(this.saveBT);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel1.Location = new System.Drawing.Point(0, 382);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(397, 100);
            this.panel1.TabIndex = 1;
            // 
            // closeBT
            // 
            this.closeBT.AllowAnimations = true;
            this.closeBT.AllowMouseEffects = true;
            this.closeBT.AllowToggling = false;
            this.closeBT.AnimationSpeed = 200;
            this.closeBT.AutoGenerateColors = false;
            this.closeBT.AutoRoundBorders = false;
            this.closeBT.AutoSizeLeftIcon = true;
            this.closeBT.AutoSizeRightIcon = true;
            this.closeBT.BackColor = System.Drawing.Color.Transparent;
            this.closeBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.closeBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("closeBT.BackgroundImage")));
            this.closeBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.closeBT.ButtonText = "Thoát";
            this.closeBT.ButtonTextMarginLeft = 0;
            this.closeBT.ColorContrastOnClick = 45;
            this.closeBT.ColorContrastOnHover = 45;
            this.closeBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.closeBT.CustomizableEdges = borderEdges5;
            this.closeBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.closeBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.closeBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.closeBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.closeBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.closeBT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.closeBT.ForeColor = System.Drawing.Color.White;
            this.closeBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.closeBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.closeBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.closeBT.IconMarginLeft = 11;
            this.closeBT.IconPadding = 10;
            this.closeBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.closeBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.closeBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.closeBT.IconSize = 25;
            this.closeBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.closeBT.IdleBorderRadius = 8;
            this.closeBT.IdleBorderThickness = 1;
            this.closeBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.closeBT.IdleIconLeftImage = null;
            this.closeBT.IdleIconRightImage = null;
            this.closeBT.IndicateFocus = false;
            this.closeBT.Location = new System.Drawing.Point(79, 49);
            this.closeBT.Name = "closeBT";
            this.closeBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.closeBT.OnDisabledState.BorderRadius = 8;
            this.closeBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.closeBT.OnDisabledState.BorderThickness = 1;
            this.closeBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.closeBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.closeBT.OnDisabledState.IconLeftImage = null;
            this.closeBT.OnDisabledState.IconRightImage = null;
            this.closeBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.closeBT.onHoverState.BorderRadius = 8;
            this.closeBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.closeBT.onHoverState.BorderThickness = 1;
            this.closeBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.closeBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.closeBT.onHoverState.IconLeftImage = null;
            this.closeBT.onHoverState.IconRightImage = null;
            this.closeBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.closeBT.OnIdleState.BorderRadius = 8;
            this.closeBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.closeBT.OnIdleState.BorderThickness = 1;
            this.closeBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.closeBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.closeBT.OnIdleState.IconLeftImage = null;
            this.closeBT.OnIdleState.IconRightImage = null;
            this.closeBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.closeBT.OnPressedState.BorderRadius = 8;
            this.closeBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.closeBT.OnPressedState.BorderThickness = 1;
            this.closeBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.closeBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.closeBT.OnPressedState.IconLeftImage = null;
            this.closeBT.OnPressedState.IconRightImage = null;
            this.closeBT.Size = new System.Drawing.Size(150, 39);
            this.closeBT.TabIndex = 32;
            this.closeBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.closeBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.closeBT.TextMarginLeft = 0;
            this.closeBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.closeBT.UseDefaultRadiusAndThickness = true;
            this.closeBT.Click += new System.EventHandler(this.closeBT_Click);
            // 
            // saveBT
            // 
            this.saveBT.AllowAnimations = true;
            this.saveBT.AllowMouseEffects = true;
            this.saveBT.AllowToggling = false;
            this.saveBT.AnimationSpeed = 200;
            this.saveBT.AutoGenerateColors = false;
            this.saveBT.AutoRoundBorders = false;
            this.saveBT.AutoSizeLeftIcon = true;
            this.saveBT.AutoSizeRightIcon = true;
            this.saveBT.BackColor = System.Drawing.Color.Transparent;
            this.saveBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.saveBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("saveBT.BackgroundImage")));
            this.saveBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBT.ButtonText = "Lưu";
            this.saveBT.ButtonTextMarginLeft = 0;
            this.saveBT.ColorContrastOnClick = 45;
            this.saveBT.ColorContrastOnHover = 45;
            this.saveBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.saveBT.CustomizableEdges = borderEdges6;
            this.saveBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.saveBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.saveBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.saveBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.saveBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.saveBT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.saveBT.ForeColor = System.Drawing.Color.White;
            this.saveBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.saveBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.saveBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.saveBT.IconMarginLeft = 11;
            this.saveBT.IconPadding = 10;
            this.saveBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.saveBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.saveBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.saveBT.IconSize = 25;
            this.saveBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.saveBT.IdleBorderRadius = 8;
            this.saveBT.IdleBorderThickness = 1;
            this.saveBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.saveBT.IdleIconLeftImage = null;
            this.saveBT.IdleIconRightImage = null;
            this.saveBT.IndicateFocus = false;
            this.saveBT.Location = new System.Drawing.Point(235, 49);
            this.saveBT.Name = "saveBT";
            this.saveBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.saveBT.OnDisabledState.BorderRadius = 8;
            this.saveBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBT.OnDisabledState.BorderThickness = 1;
            this.saveBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.saveBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.saveBT.OnDisabledState.IconLeftImage = null;
            this.saveBT.OnDisabledState.IconRightImage = null;
            this.saveBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.saveBT.onHoverState.BorderRadius = 8;
            this.saveBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBT.onHoverState.BorderThickness = 1;
            this.saveBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.saveBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.saveBT.onHoverState.IconLeftImage = null;
            this.saveBT.onHoverState.IconRightImage = null;
            this.saveBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.saveBT.OnIdleState.BorderRadius = 8;
            this.saveBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBT.OnIdleState.BorderThickness = 1;
            this.saveBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.saveBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.saveBT.OnIdleState.IconLeftImage = null;
            this.saveBT.OnIdleState.IconRightImage = null;
            this.saveBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.saveBT.OnPressedState.BorderRadius = 8;
            this.saveBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBT.OnPressedState.BorderThickness = 1;
            this.saveBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.saveBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.saveBT.OnPressedState.IconLeftImage = null;
            this.saveBT.OnPressedState.IconRightImage = null;
            this.saveBT.Size = new System.Drawing.Size(150, 39);
            this.saveBT.TabIndex = 31;
            this.saveBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.saveBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.saveBT.TextMarginLeft = 0;
            this.saveBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.saveBT.UseDefaultRadiusAndThickness = true;
            this.saveBT.Click += new System.EventHandler(this.submitBT_Click);
            // 
            // DetailForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(397, 482);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.tabControl1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "DetailForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Chi tiết";
            this.Shown += new System.EventHandler(this.DetailForm_Shown);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.accountTP.ResumeLayout(false);
            this.accountTP.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage accountTP;
        private Bunifu.UI.WinForms.BunifuTextBox firstNameTB;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox iDTB;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox lastNameTB;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox addressTB;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox emailTB;
        private Bunifu.UI.WinForms.BunifuDropdown sexDD;
        private Bunifu.UI.WinForms.BunifuDatePicker birthdayDP;
        private Bunifu.UI.WinForms.BunifuTextBox usernameTB;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label13;
        private Bunifu.UI.WinForms.BunifuTextBox passwordCfTB;
        private Bunifu.UI.WinForms.BunifuTextBox passwordTB;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton closeBT;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton saveBT;
        private System.Windows.Forms.Label changePasswordLB;
        private Bunifu.UI.WinForms.BunifuCheckBox changePasswordCB;
        private System.Windows.Forms.Label label8;
        private Bunifu.UI.WinForms.BunifuCheckBox enableCB;
    }
}