namespace QuanLyThuVien.Forms.LibrarianFroms
{
    partial class DetailForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(DetailForm));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.tabControl1 = new System.Windows.Forms.TabControl();
            this.tabPage1 = new System.Windows.Forms.TabPage();
            this.firstNameTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label1 = new System.Windows.Forms.Label();
            this.iDTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label2 = new System.Windows.Forms.Label();
            this.lastNameTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.addressTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.emailTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.sexDD = new Bunifu.UI.WinForms.BunifuDropdown();
            this.birthdayDP = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.usernameTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label14 = new System.Windows.Forms.Label();
            this.label13 = new System.Windows.Forms.Label();
            this.passwordCfTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.passwordTB = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label12 = new System.Windows.Forms.Label();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuButton1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.submitBT = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tabControl1.SuspendLayout();
            this.tabPage1.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // tabControl1
            // 
            this.tabControl1.Controls.Add(this.tabPage1);
            this.tabControl1.Controls.Add(this.tabPage2);
            this.tabControl1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabControl1.Location = new System.Drawing.Point(0, 0);
            this.tabControl1.Name = "tabControl1";
            this.tabControl1.SelectedIndex = 0;
            this.tabControl1.Size = new System.Drawing.Size(397, 482);
            this.tabControl1.TabIndex = 0;
            // 
            // tabPage1
            // 
            this.tabPage1.BackColor = System.Drawing.Color.White;
            this.tabPage1.Controls.Add(this.firstNameTB);
            this.tabPage1.Controls.Add(this.label1);
            this.tabPage1.Controls.Add(this.iDTB);
            this.tabPage1.Controls.Add(this.label2);
            this.tabPage1.Controls.Add(this.lastNameTB);
            this.tabPage1.Controls.Add(this.label3);
            this.tabPage1.Controls.Add(this.label4);
            this.tabPage1.Controls.Add(this.label5);
            this.tabPage1.Controls.Add(this.label6);
            this.tabPage1.Controls.Add(this.addressTB);
            this.tabPage1.Controls.Add(this.label7);
            this.tabPage1.Controls.Add(this.emailTB);
            this.tabPage1.Controls.Add(this.sexDD);
            this.tabPage1.Controls.Add(this.birthdayDP);
            this.tabPage1.Location = new System.Drawing.Point(4, 22);
            this.tabPage1.Name = "tabPage1";
            this.tabPage1.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage1.Size = new System.Drawing.Size(389, 456);
            this.tabPage1.TabIndex = 0;
            this.tabPage1.Text = "Thông tin";
            // 
            // firstNameTB
            // 
            this.firstNameTB.AcceptsReturn = false;
            this.firstNameTB.AcceptsTab = false;
            this.firstNameTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.firstNameTB.AnimationSpeed = 200;
            this.firstNameTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.firstNameTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.firstNameTB.BackColor = System.Drawing.Color.Transparent;
            this.firstNameTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("firstNameTB.BackgroundImage")));
            this.firstNameTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.firstNameTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.firstNameTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.firstNameTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.firstNameTB.BorderRadius = 8;
            this.firstNameTB.BorderThickness = 1;
            this.firstNameTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.firstNameTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNameTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.firstNameTB.DefaultText = "";
            this.firstNameTB.FillColor = System.Drawing.Color.White;
            this.firstNameTB.HideSelection = true;
            this.firstNameTB.IconLeft = null;
            this.firstNameTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNameTB.IconPadding = 10;
            this.firstNameTB.IconRight = null;
            this.firstNameTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.firstNameTB.Lines = new string[0];
            this.firstNameTB.Location = new System.Drawing.Point(121, 92);
            this.firstNameTB.MaxLength = 32767;
            this.firstNameTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.firstNameTB.Modified = false;
            this.firstNameTB.Multiline = false;
            this.firstNameTB.Name = "firstNameTB";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameTB.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.firstNameTB.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameTB.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.firstNameTB.OnIdleState = stateProperties4;
            this.firstNameTB.Padding = new System.Windows.Forms.Padding(3);
            this.firstNameTB.PasswordChar = '\0';
            this.firstNameTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.firstNameTB.PlaceholderText = "Enter text";
            this.firstNameTB.ReadOnly = false;
            this.firstNameTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.firstNameTB.SelectedText = "";
            this.firstNameTB.SelectionLength = 0;
            this.firstNameTB.SelectionStart = 0;
            this.firstNameTB.ShortcutsEnabled = true;
            this.firstNameTB.Size = new System.Drawing.Size(260, 37);
            this.firstNameTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.firstNameTB.TabIndex = 35;
            this.firstNameTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.firstNameTB.TextMarginBottom = 0;
            this.firstNameTB.TextMarginLeft = 3;
            this.firstNameTB.TextMarginTop = 0;
            this.firstNameTB.TextPlaceholder = "Enter text";
            this.firstNameTB.UseSystemPasswordChar = false;
            this.firstNameTB.WordWrap = true;
            // 
            // label1
            // 
            this.label1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(96, 28);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(19, 15);
            this.label1.TabIndex = 30;
            this.label1.Text = "ID";
            // 
            // iDTB
            // 
            this.iDTB.AcceptsReturn = false;
            this.iDTB.AcceptsTab = false;
            this.iDTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.iDTB.AnimationSpeed = 200;
            this.iDTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.iDTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.iDTB.BackColor = System.Drawing.Color.Transparent;
            this.iDTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("iDTB.BackgroundImage")));
            this.iDTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.iDTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.iDTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.iDTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.iDTB.BorderRadius = 8;
            this.iDTB.BorderThickness = 1;
            this.iDTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.iDTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.iDTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.iDTB.DefaultText = "";
            this.iDTB.Enabled = false;
            this.iDTB.FillColor = System.Drawing.Color.White;
            this.iDTB.HideSelection = true;
            this.iDTB.IconLeft = null;
            this.iDTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.iDTB.IconPadding = 10;
            this.iDTB.IconRight = null;
            this.iDTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.iDTB.Lines = new string[0];
            this.iDTB.Location = new System.Drawing.Point(121, 6);
            this.iDTB.MaxLength = 32767;
            this.iDTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.iDTB.Modified = false;
            this.iDTB.Multiline = false;
            this.iDTB.Name = "iDTB";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.iDTB.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.iDTB.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.iDTB.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.iDTB.OnIdleState = stateProperties8;
            this.iDTB.Padding = new System.Windows.Forms.Padding(3);
            this.iDTB.PasswordChar = '\0';
            this.iDTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.iDTB.PlaceholderText = "Enter text";
            this.iDTB.ReadOnly = false;
            this.iDTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.iDTB.SelectedText = "";
            this.iDTB.SelectionLength = 0;
            this.iDTB.SelectionStart = 0;
            this.iDTB.ShortcutsEnabled = true;
            this.iDTB.Size = new System.Drawing.Size(260, 37);
            this.iDTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.iDTB.TabIndex = 31;
            this.iDTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.iDTB.TextMarginBottom = 0;
            this.iDTB.TextMarginLeft = 3;
            this.iDTB.TextMarginTop = 0;
            this.iDTB.TextPlaceholder = "Enter text";
            this.iDTB.UseSystemPasswordChar = false;
            this.iDTB.WordWrap = true;
            // 
            // label2
            // 
            this.label2.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(92, 71);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(23, 15);
            this.label2.TabIndex = 32;
            this.label2.Text = "Họ";
            // 
            // lastNameTB
            // 
            this.lastNameTB.AcceptsReturn = false;
            this.lastNameTB.AcceptsTab = false;
            this.lastNameTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.lastNameTB.AnimationSpeed = 200;
            this.lastNameTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.lastNameTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.lastNameTB.BackColor = System.Drawing.Color.Transparent;
            this.lastNameTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("lastNameTB.BackgroundImage")));
            this.lastNameTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.lastNameTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.lastNameTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.lastNameTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.lastNameTB.BorderRadius = 8;
            this.lastNameTB.BorderThickness = 1;
            this.lastNameTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.lastNameTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.lastNameTB.DefaultText = "";
            this.lastNameTB.FillColor = System.Drawing.Color.White;
            this.lastNameTB.HideSelection = true;
            this.lastNameTB.IconLeft = null;
            this.lastNameTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTB.IconPadding = 10;
            this.lastNameTB.IconRight = null;
            this.lastNameTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.lastNameTB.Lines = new string[0];
            this.lastNameTB.Location = new System.Drawing.Point(121, 49);
            this.lastNameTB.MaxLength = 32767;
            this.lastNameTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.lastNameTB.Modified = false;
            this.lastNameTB.Multiline = false;
            this.lastNameTB.Name = "lastNameTB";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTB.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.lastNameTB.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTB.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.lastNameTB.OnIdleState = stateProperties12;
            this.lastNameTB.Padding = new System.Windows.Forms.Padding(3);
            this.lastNameTB.PasswordChar = '\0';
            this.lastNameTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.lastNameTB.PlaceholderText = "Enter text";
            this.lastNameTB.ReadOnly = false;
            this.lastNameTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.lastNameTB.SelectedText = "";
            this.lastNameTB.SelectionLength = 0;
            this.lastNameTB.SelectionStart = 0;
            this.lastNameTB.ShortcutsEnabled = true;
            this.lastNameTB.Size = new System.Drawing.Size(260, 37);
            this.lastNameTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.lastNameTB.TabIndex = 33;
            this.lastNameTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.lastNameTB.TextMarginBottom = 0;
            this.lastNameTB.TextMarginLeft = 3;
            this.lastNameTB.TextMarginTop = 0;
            this.lastNameTB.TextPlaceholder = "Enter text";
            this.lastNameTB.UseSystemPasswordChar = false;
            this.lastNameTB.WordWrap = true;
            // 
            // label3
            // 
            this.label3.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(87, 114);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(28, 15);
            this.label3.TabIndex = 34;
            this.label3.Text = "Tên";
            // 
            // label4
            // 
            this.label4.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(63, 152);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(52, 15);
            this.label4.TabIndex = 36;
            this.label4.Text = "Giới tính";
            // 
            // label5
            // 
            this.label5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(56, 190);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(59, 15);
            this.label5.TabIndex = 37;
            this.label5.Text = "Sinh nhật";
            // 
            // label6
            // 
            this.label6.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(76, 233);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(39, 15);
            this.label6.TabIndex = 38;
            this.label6.Text = "Email";
            // 
            // addressTB
            // 
            this.addressTB.AcceptsReturn = false;
            this.addressTB.AcceptsTab = false;
            this.addressTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.addressTB.AnimationSpeed = 200;
            this.addressTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.addressTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.addressTB.BackColor = System.Drawing.Color.Transparent;
            this.addressTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addressTB.BackgroundImage")));
            this.addressTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.addressTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addressTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.addressTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.addressTB.BorderRadius = 8;
            this.addressTB.BorderThickness = 1;
            this.addressTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.addressTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.addressTB.DefaultText = "";
            this.addressTB.FillColor = System.Drawing.Color.White;
            this.addressTB.HideSelection = true;
            this.addressTB.IconLeft = null;
            this.addressTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTB.IconPadding = 10;
            this.addressTB.IconRight = null;
            this.addressTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.addressTB.Lines = new string[0];
            this.addressTB.Location = new System.Drawing.Point(121, 254);
            this.addressTB.MaxLength = 32767;
            this.addressTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.addressTB.Modified = false;
            this.addressTB.Multiline = false;
            this.addressTB.Name = "addressTB";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTB.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.addressTB.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTB.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.addressTB.OnIdleState = stateProperties16;
            this.addressTB.Padding = new System.Windows.Forms.Padding(3);
            this.addressTB.PasswordChar = '\0';
            this.addressTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.addressTB.PlaceholderText = "Enter text";
            this.addressTB.ReadOnly = false;
            this.addressTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.addressTB.SelectedText = "";
            this.addressTB.SelectionLength = 0;
            this.addressTB.SelectionStart = 0;
            this.addressTB.ShortcutsEnabled = true;
            this.addressTB.Size = new System.Drawing.Size(260, 37);
            this.addressTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.addressTB.TabIndex = 43;
            this.addressTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.addressTB.TextMarginBottom = 0;
            this.addressTB.TextMarginLeft = 3;
            this.addressTB.TextMarginTop = 0;
            this.addressTB.TextPlaceholder = "Enter text";
            this.addressTB.UseSystemPasswordChar = false;
            this.addressTB.WordWrap = true;
            // 
            // label7
            // 
            this.label7.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label7.Location = new System.Drawing.Point(70, 276);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(45, 15);
            this.label7.TabIndex = 39;
            this.label7.Text = "Địa chỉ";
            // 
            // emailTB
            // 
            this.emailTB.AcceptsReturn = false;
            this.emailTB.AcceptsTab = false;
            this.emailTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.emailTB.AnimationSpeed = 200;
            this.emailTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.emailTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.emailTB.BackColor = System.Drawing.Color.Transparent;
            this.emailTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("emailTB.BackgroundImage")));
            this.emailTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.emailTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.emailTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.emailTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.emailTB.BorderRadius = 8;
            this.emailTB.BorderThickness = 1;
            this.emailTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.emailTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.emailTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.emailTB.DefaultText = "";
            this.emailTB.FillColor = System.Drawing.Color.White;
            this.emailTB.HideSelection = true;
            this.emailTB.IconLeft = null;
            this.emailTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailTB.IconPadding = 10;
            this.emailTB.IconRight = null;
            this.emailTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.emailTB.Lines = new string[0];
            this.emailTB.Location = new System.Drawing.Point(121, 211);
            this.emailTB.MaxLength = 32767;
            this.emailTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.emailTB.Modified = false;
            this.emailTB.Multiline = false;
            this.emailTB.Name = "emailTB";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailTB.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.emailTB.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailTB.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.emailTB.OnIdleState = stateProperties20;
            this.emailTB.Padding = new System.Windows.Forms.Padding(3);
            this.emailTB.PasswordChar = '\0';
            this.emailTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.emailTB.PlaceholderText = "Enter text";
            this.emailTB.ReadOnly = false;
            this.emailTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.emailTB.SelectedText = "";
            this.emailTB.SelectionLength = 0;
            this.emailTB.SelectionStart = 0;
            this.emailTB.ShortcutsEnabled = true;
            this.emailTB.Size = new System.Drawing.Size(260, 37);
            this.emailTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.emailTB.TabIndex = 42;
            this.emailTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.emailTB.TextMarginBottom = 0;
            this.emailTB.TextMarginLeft = 3;
            this.emailTB.TextMarginTop = 0;
            this.emailTB.TextPlaceholder = "Enter text";
            this.emailTB.UseSystemPasswordChar = false;
            this.emailTB.WordWrap = true;
            // 
            // sexDD
            // 
            this.sexDD.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.sexDD.BackColor = System.Drawing.Color.Transparent;
            this.sexDD.BackgroundColor = System.Drawing.Color.White;
            this.sexDD.BorderColor = System.Drawing.Color.Silver;
            this.sexDD.BorderRadius = 8;
            this.sexDD.Color = System.Drawing.Color.Silver;
            this.sexDD.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.sexDD.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.sexDD.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.sexDD.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.sexDD.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.sexDD.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.sexDD.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.sexDD.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.sexDD.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.sexDD.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.sexDD.FillDropDown = true;
            this.sexDD.FillIndicator = false;
            this.sexDD.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.sexDD.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.sexDD.ForeColor = System.Drawing.Color.Black;
            this.sexDD.FormattingEnabled = true;
            this.sexDD.Icon = null;
            this.sexDD.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.sexDD.IndicatorColor = System.Drawing.Color.Gray;
            this.sexDD.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.sexDD.ItemBackColor = System.Drawing.Color.White;
            this.sexDD.ItemBorderColor = System.Drawing.Color.White;
            this.sexDD.ItemForeColor = System.Drawing.Color.Black;
            this.sexDD.ItemHeight = 26;
            this.sexDD.ItemHighLightColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.sexDD.ItemHighLightForeColor = System.Drawing.Color.White;
            this.sexDD.ItemTopMargin = 3;
            this.sexDD.Location = new System.Drawing.Point(121, 135);
            this.sexDD.Name = "sexDD";
            this.sexDD.Size = new System.Drawing.Size(260, 32);
            this.sexDD.TabIndex = 40;
            this.sexDD.Text = null;
            this.sexDD.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.sexDD.TextLeftMargin = 5;
            // 
            // birthdayDP
            // 
            this.birthdayDP.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.birthdayDP.BackColor = System.Drawing.Color.Transparent;
            this.birthdayDP.BorderRadius = 8;
            this.birthdayDP.Color = System.Drawing.Color.Silver;
            this.birthdayDP.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.birthdayDP.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.birthdayDP.DisabledColor = System.Drawing.Color.Gray;
            this.birthdayDP.DisplayWeekNumbers = false;
            this.birthdayDP.DPHeight = 0;
            this.birthdayDP.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.birthdayDP.FillDatePicker = false;
            this.birthdayDP.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.birthdayDP.ForeColor = System.Drawing.Color.Black;
            this.birthdayDP.Icon = ((System.Drawing.Image)(resources.GetObject("birthdayDP.Icon")));
            this.birthdayDP.IconColor = System.Drawing.Color.Gray;
            this.birthdayDP.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.birthdayDP.LeftTextMargin = 5;
            this.birthdayDP.Location = new System.Drawing.Point(121, 173);
            this.birthdayDP.MinimumSize = new System.Drawing.Size(4, 32);
            this.birthdayDP.Name = "birthdayDP";
            this.birthdayDP.Size = new System.Drawing.Size(260, 32);
            this.birthdayDP.TabIndex = 41;
            // 
            // tabPage2
            // 
            this.tabPage2.BackColor = System.Drawing.Color.White;
            this.tabPage2.Controls.Add(this.usernameTB);
            this.tabPage2.Controls.Add(this.label14);
            this.tabPage2.Controls.Add(this.label13);
            this.tabPage2.Controls.Add(this.passwordCfTB);
            this.tabPage2.Controls.Add(this.passwordTB);
            this.tabPage2.Controls.Add(this.label12);
            this.tabPage2.Location = new System.Drawing.Point(4, 22);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(389, 456);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "Tài khoản";
            // 
            // usernameTB
            // 
            this.usernameTB.AcceptsReturn = false;
            this.usernameTB.AcceptsTab = false;
            this.usernameTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.usernameTB.AnimationSpeed = 200;
            this.usernameTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.usernameTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.usernameTB.BackColor = System.Drawing.Color.Transparent;
            this.usernameTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("usernameTB.BackgroundImage")));
            this.usernameTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.usernameTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.usernameTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.usernameTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.usernameTB.BorderRadius = 8;
            this.usernameTB.BorderThickness = 1;
            this.usernameTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.usernameTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.usernameTB.DefaultText = "";
            this.usernameTB.Enabled = false;
            this.usernameTB.FillColor = System.Drawing.Color.White;
            this.usernameTB.HideSelection = true;
            this.usernameTB.IconLeft = null;
            this.usernameTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTB.IconPadding = 10;
            this.usernameTB.IconRight = null;
            this.usernameTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.usernameTB.Lines = new string[0];
            this.usernameTB.Location = new System.Drawing.Point(121, 6);
            this.usernameTB.MaxLength = 32767;
            this.usernameTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.usernameTB.Modified = false;
            this.usernameTB.Multiline = false;
            this.usernameTB.Name = "usernameTB";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTB.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.usernameTB.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTB.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.usernameTB.OnIdleState = stateProperties24;
            this.usernameTB.Padding = new System.Windows.Forms.Padding(3);
            this.usernameTB.PasswordChar = '\0';
            this.usernameTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.usernameTB.PlaceholderText = "Enter text";
            this.usernameTB.ReadOnly = false;
            this.usernameTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.usernameTB.SelectedText = "";
            this.usernameTB.SelectionLength = 0;
            this.usernameTB.SelectionStart = 0;
            this.usernameTB.ShortcutsEnabled = true;
            this.usernameTB.Size = new System.Drawing.Size(260, 37);
            this.usernameTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.usernameTB.TabIndex = 38;
            this.usernameTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.usernameTB.TextMarginBottom = 0;
            this.usernameTB.TextMarginLeft = 3;
            this.usernameTB.TextMarginTop = 0;
            this.usernameTB.TextPlaceholder = "Enter text";
            this.usernameTB.UseSystemPasswordChar = false;
            this.usernameTB.WordWrap = true;
            // 
            // label14
            // 
            this.label14.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label14.AutoSize = true;
            this.label14.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label14.Location = new System.Drawing.Point(96, 28);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(19, 15);
            this.label14.TabIndex = 37;
            this.label14.Text = "ID";
            // 
            // label13
            // 
            this.label13.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label13.AutoSize = true;
            this.label13.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label13.Location = new System.Drawing.Point(57, 71);
            this.label13.Name = "label13";
            this.label13.Size = new System.Drawing.Size(58, 15);
            this.label13.TabIndex = 39;
            this.label13.Text = "Mật khẩu";
            // 
            // passwordCfTB
            // 
            this.passwordCfTB.AcceptsReturn = false;
            this.passwordCfTB.AcceptsTab = false;
            this.passwordCfTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.passwordCfTB.AnimationSpeed = 200;
            this.passwordCfTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.passwordCfTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.passwordCfTB.BackColor = System.Drawing.Color.Transparent;
            this.passwordCfTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("passwordCfTB.BackgroundImage")));
            this.passwordCfTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.passwordCfTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.passwordCfTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.passwordCfTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.passwordCfTB.BorderRadius = 8;
            this.passwordCfTB.BorderThickness = 1;
            this.passwordCfTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.passwordCfTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordCfTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.passwordCfTB.DefaultText = "";
            this.passwordCfTB.FillColor = System.Drawing.Color.White;
            this.passwordCfTB.HideSelection = true;
            this.passwordCfTB.IconLeft = null;
            this.passwordCfTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordCfTB.IconPadding = 10;
            this.passwordCfTB.IconRight = null;
            this.passwordCfTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordCfTB.Lines = new string[0];
            this.passwordCfTB.Location = new System.Drawing.Point(121, 92);
            this.passwordCfTB.MaxLength = 32767;
            this.passwordCfTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.passwordCfTB.Modified = false;
            this.passwordCfTB.Multiline = false;
            this.passwordCfTB.Name = "passwordCfTB";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordCfTB.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.passwordCfTB.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordCfTB.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordCfTB.OnIdleState = stateProperties28;
            this.passwordCfTB.Padding = new System.Windows.Forms.Padding(3);
            this.passwordCfTB.PasswordChar = '\0';
            this.passwordCfTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.passwordCfTB.PlaceholderText = "Enter text";
            this.passwordCfTB.ReadOnly = false;
            this.passwordCfTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.passwordCfTB.SelectedText = "";
            this.passwordCfTB.SelectionLength = 0;
            this.passwordCfTB.SelectionStart = 0;
            this.passwordCfTB.ShortcutsEnabled = true;
            this.passwordCfTB.Size = new System.Drawing.Size(260, 37);
            this.passwordCfTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.passwordCfTB.TabIndex = 42;
            this.passwordCfTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.passwordCfTB.TextMarginBottom = 0;
            this.passwordCfTB.TextMarginLeft = 3;
            this.passwordCfTB.TextMarginTop = 0;
            this.passwordCfTB.TextPlaceholder = "Enter text";
            this.passwordCfTB.UseSystemPasswordChar = false;
            this.passwordCfTB.WordWrap = true;
            // 
            // passwordTB
            // 
            this.passwordTB.AcceptsReturn = false;
            this.passwordTB.AcceptsTab = false;
            this.passwordTB.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.passwordTB.AnimationSpeed = 200;
            this.passwordTB.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.passwordTB.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.passwordTB.BackColor = System.Drawing.Color.Transparent;
            this.passwordTB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("passwordTB.BackgroundImage")));
            this.passwordTB.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.passwordTB.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.passwordTB.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.passwordTB.BorderColorIdle = System.Drawing.Color.Silver;
            this.passwordTB.BorderRadius = 8;
            this.passwordTB.BorderThickness = 1;
            this.passwordTB.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.passwordTB.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordTB.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.passwordTB.DefaultText = "";
            this.passwordTB.FillColor = System.Drawing.Color.White;
            this.passwordTB.HideSelection = true;
            this.passwordTB.IconLeft = null;
            this.passwordTB.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordTB.IconPadding = 10;
            this.passwordTB.IconRight = null;
            this.passwordTB.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.passwordTB.Lines = new string[0];
            this.passwordTB.Location = new System.Drawing.Point(121, 49);
            this.passwordTB.MaxLength = 32767;
            this.passwordTB.MinimumSize = new System.Drawing.Size(1, 1);
            this.passwordTB.Modified = false;
            this.passwordTB.Multiline = false;
            this.passwordTB.Name = "passwordTB";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordTB.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.passwordTB.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordTB.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.passwordTB.OnIdleState = stateProperties32;
            this.passwordTB.Padding = new System.Windows.Forms.Padding(3);
            this.passwordTB.PasswordChar = '\0';
            this.passwordTB.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.passwordTB.PlaceholderText = "Enter text";
            this.passwordTB.ReadOnly = false;
            this.passwordTB.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.passwordTB.SelectedText = "";
            this.passwordTB.SelectionLength = 0;
            this.passwordTB.SelectionStart = 0;
            this.passwordTB.ShortcutsEnabled = true;
            this.passwordTB.Size = new System.Drawing.Size(260, 37);
            this.passwordTB.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.passwordTB.TabIndex = 40;
            this.passwordTB.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.passwordTB.TextMarginBottom = 0;
            this.passwordTB.TextMarginLeft = 3;
            this.passwordTB.TextMarginTop = 0;
            this.passwordTB.TextPlaceholder = "Enter text";
            this.passwordTB.UseSystemPasswordChar = false;
            this.passwordTB.WordWrap = true;
            // 
            // label12
            // 
            this.label12.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label12.AutoSize = true;
            this.label12.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label12.Location = new System.Drawing.Point(8, 114);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(107, 15);
            this.label12.TabIndex = 41;
            this.label12.Text = "Nhập lại mật khẩu";
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.White;
            this.panel1.Controls.Add(this.bunifuButton1);
            this.panel1.Controls.Add(this.submitBT);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel1.Location = new System.Drawing.Point(0, 382);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(397, 100);
            this.panel1.TabIndex = 1;
            // 
            // bunifuButton1
            // 
            this.bunifuButton1.AllowAnimations = true;
            this.bunifuButton1.AllowMouseEffects = true;
            this.bunifuButton1.AllowToggling = false;
            this.bunifuButton1.AnimationSpeed = 200;
            this.bunifuButton1.AutoGenerateColors = false;
            this.bunifuButton1.AutoRoundBorders = false;
            this.bunifuButton1.AutoSizeLeftIcon = true;
            this.bunifuButton1.AutoSizeRightIcon = true;
            this.bunifuButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton1.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton1.BackgroundImage")));
            this.bunifuButton1.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.ButtonText = "Thoát";
            this.bunifuButton1.ButtonTextMarginLeft = 0;
            this.bunifuButton1.ColorContrastOnClick = 45;
            this.bunifuButton1.ColorContrastOnHover = 45;
            this.bunifuButton1.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton1.CustomizableEdges = borderEdges1;
            this.bunifuButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton1.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton1.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton1.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton1.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton1.IconMarginLeft = 11;
            this.bunifuButton1.IconPadding = 10;
            this.bunifuButton1.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton1.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton1.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton1.IconSize = 25;
            this.bunifuButton1.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton1.IdleBorderRadius = 8;
            this.bunifuButton1.IdleBorderThickness = 1;
            this.bunifuButton1.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton1.IdleIconLeftImage = null;
            this.bunifuButton1.IdleIconRightImage = null;
            this.bunifuButton1.IndicateFocus = false;
            this.bunifuButton1.Location = new System.Drawing.Point(79, 49);
            this.bunifuButton1.Name = "bunifuButton1";
            this.bunifuButton1.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton1.OnDisabledState.BorderRadius = 8;
            this.bunifuButton1.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnDisabledState.BorderThickness = 1;
            this.bunifuButton1.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton1.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton1.OnDisabledState.IconLeftImage = null;
            this.bunifuButton1.OnDisabledState.IconRightImage = null;
            this.bunifuButton1.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.bunifuButton1.onHoverState.BorderRadius = 8;
            this.bunifuButton1.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.onHoverState.BorderThickness = 1;
            this.bunifuButton1.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.bunifuButton1.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.onHoverState.IconLeftImage = null;
            this.bunifuButton1.onHoverState.IconRightImage = null;
            this.bunifuButton1.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnIdleState.BorderRadius = 8;
            this.bunifuButton1.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnIdleState.BorderThickness = 1;
            this.bunifuButton1.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.bunifuButton1.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnIdleState.IconLeftImage = null;
            this.bunifuButton1.OnIdleState.IconRightImage = null;
            this.bunifuButton1.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.bunifuButton1.OnPressedState.BorderRadius = 8;
            this.bunifuButton1.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton1.OnPressedState.BorderThickness = 1;
            this.bunifuButton1.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.bunifuButton1.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton1.OnPressedState.IconLeftImage = null;
            this.bunifuButton1.OnPressedState.IconRightImage = null;
            this.bunifuButton1.Size = new System.Drawing.Size(150, 39);
            this.bunifuButton1.TabIndex = 32;
            this.bunifuButton1.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton1.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton1.TextMarginLeft = 0;
            this.bunifuButton1.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton1.UseDefaultRadiusAndThickness = true;
            // 
            // submitBT
            // 
            this.submitBT.AllowAnimations = true;
            this.submitBT.AllowMouseEffects = true;
            this.submitBT.AllowToggling = false;
            this.submitBT.AnimationSpeed = 200;
            this.submitBT.AutoGenerateColors = false;
            this.submitBT.AutoRoundBorders = false;
            this.submitBT.AutoSizeLeftIcon = true;
            this.submitBT.AutoSizeRightIcon = true;
            this.submitBT.BackColor = System.Drawing.Color.Transparent;
            this.submitBT.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.submitBT.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("submitBT.BackgroundImage")));
            this.submitBT.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.submitBT.ButtonText = "Tạo";
            this.submitBT.ButtonTextMarginLeft = 0;
            this.submitBT.ColorContrastOnClick = 45;
            this.submitBT.ColorContrastOnHover = 45;
            this.submitBT.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.submitBT.CustomizableEdges = borderEdges2;
            this.submitBT.DialogResult = System.Windows.Forms.DialogResult.None;
            this.submitBT.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.submitBT.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.submitBT.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.submitBT.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.submitBT.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.submitBT.ForeColor = System.Drawing.Color.White;
            this.submitBT.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.submitBT.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.submitBT.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.submitBT.IconMarginLeft = 11;
            this.submitBT.IconPadding = 10;
            this.submitBT.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.submitBT.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.submitBT.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.submitBT.IconSize = 25;
            this.submitBT.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.submitBT.IdleBorderRadius = 8;
            this.submitBT.IdleBorderThickness = 1;
            this.submitBT.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.submitBT.IdleIconLeftImage = null;
            this.submitBT.IdleIconRightImage = null;
            this.submitBT.IndicateFocus = false;
            this.submitBT.Location = new System.Drawing.Point(235, 49);
            this.submitBT.Name = "submitBT";
            this.submitBT.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.submitBT.OnDisabledState.BorderRadius = 8;
            this.submitBT.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.submitBT.OnDisabledState.BorderThickness = 1;
            this.submitBT.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.submitBT.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.submitBT.OnDisabledState.IconLeftImage = null;
            this.submitBT.OnDisabledState.IconRightImage = null;
            this.submitBT.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.submitBT.onHoverState.BorderRadius = 8;
            this.submitBT.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.submitBT.onHoverState.BorderThickness = 1;
            this.submitBT.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(102)))), ((int)(((byte)(83)))), ((int)(((byte)(164)))));
            this.submitBT.onHoverState.ForeColor = System.Drawing.Color.White;
            this.submitBT.onHoverState.IconLeftImage = null;
            this.submitBT.onHoverState.IconRightImage = null;
            this.submitBT.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.submitBT.OnIdleState.BorderRadius = 8;
            this.submitBT.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.submitBT.OnIdleState.BorderThickness = 1;
            this.submitBT.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(82)))), ((int)(((byte)(63)))), ((int)(((byte)(144)))));
            this.submitBT.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.submitBT.OnIdleState.IconLeftImage = null;
            this.submitBT.OnIdleState.IconRightImage = null;
            this.submitBT.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.submitBT.OnPressedState.BorderRadius = 8;
            this.submitBT.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.submitBT.OnPressedState.BorderThickness = 1;
            this.submitBT.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(92)))), ((int)(((byte)(73)))), ((int)(((byte)(154)))));
            this.submitBT.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.submitBT.OnPressedState.IconLeftImage = null;
            this.submitBT.OnPressedState.IconRightImage = null;
            this.submitBT.Size = new System.Drawing.Size(150, 39);
            this.submitBT.TabIndex = 31;
            this.submitBT.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.submitBT.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.submitBT.TextMarginLeft = 0;
            this.submitBT.TextPadding = new System.Windows.Forms.Padding(0);
            this.submitBT.UseDefaultRadiusAndThickness = true;
            this.submitBT.Click += new System.EventHandler(this.submitBT_Click);
            // 
            // DetailForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(397, 482);
            this.Controls.Add(this.panel1);
            this.Controls.Add(this.tabControl1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "DetailForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Chi tiết";
            this.Shown += new System.EventHandler(this.DetailForm_Shown);
            this.tabControl1.ResumeLayout(false);
            this.tabPage1.ResumeLayout(false);
            this.tabPage1.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TabControl tabControl1;
        private System.Windows.Forms.TabPage tabPage1;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuTextBox firstNameTB;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox iDTB;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuTextBox lastNameTB;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private Bunifu.UI.WinForms.BunifuTextBox addressTB;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuTextBox emailTB;
        private Bunifu.UI.WinForms.BunifuDropdown sexDD;
        private Bunifu.UI.WinForms.BunifuDatePicker birthdayDP;
        private Bunifu.UI.WinForms.BunifuTextBox usernameTB;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label label13;
        private Bunifu.UI.WinForms.BunifuTextBox passwordCfTB;
        private Bunifu.UI.WinForms.BunifuTextBox passwordTB;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton submitBT;
    }
}